### ISSUE TITLE
Lock editing to prevent multiple users overwriting each other

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#1011]
Now that we have the ability to have multiple users owning a module, we'll need to lock editing to prevent multiple users from overwriting each other's work.

In Obojobo Classic we just used a key in memcache to keep track of this - `user x is editing document y` (with a 5 minute auto-expire).  The key is refreshed every time the session ping occurs.

If another user attempts to edit a document, the ui blocks the action and tells them that Prof. X is editing it right now.

Make sure to deal with the chance that your own current editing rights can expire while you've got a tab backgrounded.

**Comment by iturgeon** [comment]
Notes on our most recent ides:

* Check when I save that there isn't a newer version that's been saved by someone else (keep track of the latest known version in my editor)
* When opening an editor -check if someone else has recently opened an editor and give me a strong warning with the ability to continue editing (flip up the emergency switch cover before flipping it on)

**Comment by zachberry** [comment]
This is being done on #1051
