### ISSUE TITLE
Don't allow modules with blank titles

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1037]
In the visual editor you can have a blank title - if you do this the UI gets upset since the title string is now an empty element. We don't really want modules to have blank titles anyway so this should be prevented in the editor. If someone creates a blank title in XML and views it in the visual editor then at least the UI should display the empty string in a way that doesn't mess up the page.

**Comment by FrenjaminBanklin** [comment]
So we've got [this code in the document editor Header component](https://github.com/ucfopen/Obojobo/blob/e4b7a3861052ee51381064bd22808f97db4dc1fb/packages/app/obojobo-document-engine/src/scripts/oboeditor/components/navigation/header.js#L16-L22) that's specifically looking at what the module title is being changed to and setting it to an empty string if it's somehow not a string at all.

So - would it make more sense to put a check after this that throws away the empty string and just uses the old title, then puts an alert of some kind on the screen indicating that you can't make the module title an empty string?
Or would it make more sense to build some functionality into MoreInfoBox to enable optional validation on input fields?

**Comment by FrenjaminBanklin** [comment]
Went ahead with the latter option when setting a module's title through the MoreInfoBox.

Indicating that an empty string isn't valid in the editor page's module title input field is going to be a bit different - it'll only actually go to rename the module when the input blurs (enter key, escape key, control/command s, clicking away, etc.). Assuming there'll be a new check there to prevent the normal behavior if the title is an empty string, would it be better to throw a window alert indicating the problem, to add a class of some kind to the input itself, or some other option that I'm not thinking of?
