### ISSUE TITLE
Editors not always saving as expected

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1070]
Found 3 cases where the editors are not saving as expected.

1. In the visual editor if you rename a module the 'Saved!' text shows up but the module isn't actually saved.
2. If you switch to the XML editor the module is automatically saved, but if you switch to the Visual Editor it's not, and if you haven't saved any XML work is lost. I assume the same problem exists for the JSON editor but I haven't tested it.
3. In the XML editor if you have invalid XML and attempt to save you should see an error dialog pop up. However if you use the keyboard shortcut (cmd/ctrl+s) to save you'll see 'Saved!' with no indication that something went wrong.

**Comment by vutoan1245** [comment]
For point number 2: `onSave()` was called but it is an asynchronous function. As a result, the editor switches before it is done saving. (File reference: `obojobo-document-engine/src/scripts/oboeditor/components/toolbars/view-menu.js`)

**Comment by iturgeon** [comment]
I just noticed when I fetched all the repos that you committed some code for this.  I went pretty deep into trying to understand & simplify how editor-app handles it's 3 different states - ended up in some wide-sweeping changes on my branch https://github.com/ucfopen/Obojobo/pull/1079
