### ISSUE TITLE
XML/JSON editor allows invalid document

### ISSUE THREAD

**Issue by vutoan1245** [ucfopen/Obojobo#1085]
Both XML/JSON editors allow users to save invalid Obojobo documents. The next time they open it, Obojobo editor will crash.

Example: `"type": "ObojoboDraft.Modules.Invalid"` in a JSON document.

There should be a feature to prevent an invalid document from being saved.

Relate issue: #1083

**Comment by ctcuff** [comment]
Related, if you add invalid XML and save, the module with the invalid XML has no title
