### ISSUE TITLE
Outdated browser error state

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1086]
We don't support IE11 (for example) but users may still attempt to use IE11, so ideally we need an error state when the users browser won't work. This might also be more of an issue with an old Android phone or someone stuck on an old version of FF or Chrome.

I'm thinking of something like this which would check for any features we're not poly-filling:

```javascript
if(!window.fetch || !Number.isFinite || !Array.find /* || ... */) {
    // Display an error here, like 'Your browser is out of date'
}
```

**Comment by iturgeon** [comment]
I think we could get a little more advanced.  We're using browserlist to generate polyfills automatically, let's use that same list of browsers to test useragents.  

Something like this: https://dev.to/amplifr/outdated-browser-detection-with-browserslist-10co
