### ISSUE TITLE
Math Equation popup can sit under content when inside a Question Solution

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1137]
Found in the wild:

![image](https://user-images.githubusercontent.com/73479/73489845-52f34580-4379-11ea-877b-ba3dbd4d047e.png)

My first idea is to give the currently focused in chunk a z-index higher than the other chunks. A better solution would be able to have the popup exist on a layer above the content (Portals?).

**Comment by ctcuff** [comment]
I think the same problem also applies to the MoreInfoBox:
<img width="919" alt="dialog-render-errors" src="https://user-images.githubusercontent.com/7400747/74251623-6926cd00-4cba-11ea-90e4-dfbe0199189e.png">
