### ISSUE TITLE
Converting & to &amp; in XML (and other special characters)

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1141]
To replicate:
1. In the visual editor type an ampersand
2. Switch to XML editing
3. Attempt to save the document

Result: Saving will fail since the & should be written as &amp;

We need to somehow convert this character and other special characters that need to be handled in XML when switching from XML, and restore the non-special version when switching away from XML

**Comment by zachberry** [comment]
This is also happening with `<` and `>` symbols

**Comment by qwertynerd97** [comment]
Currently, we have code to escape XML special characters, but it is only being run on attributes, and it does not escape apostrophes, <, or >.  We need to add those three characters, and add the xmlEncode() to the textGroup parsing
