### ISSUE TITLE
lti launches need to detect when lis_person_sourcedid is not sent, and error out.

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#116]
<a href="https://github.com/iturgeon"><img src="https://avatars2.githubusercontent.com/u/73480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iturgeon](https://github.com/iturgeon)**
_Thursday Feb 15, 2018 at 21:20 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/118_

----

when the lti is configured without 'public' the lis_person_sourceid is not sent and for some reason all users end up as the same user:
```10   | 2017-03-31 21:18:09.636153+00 | guest        | guest@obojobo.ucf.edu            | Zachary      | Berry       | [u'Instructor'] ```

* [ ] Detect when the sourceid is missing and display an error
* [ ] Research why those users all ended up as one specific user
* [ ] add tests to support the resulting code.

**Comment by rmanbaird** [comment]
tested dev/5 on Canvas with privacy_level set to "anonymous", "name_only", "e-mail_only" and all three properly error out on launch with "Server Error: There was a problem creating your account."

**Comment by rmanbaird** [comment]
verified [user.js] (https://github.com/ucfopen/Obojobo/blob/7d93636e2c9efe6b8ac3ba02ffd978018ece72b5/packages/obojobo-express/models/user.js#L14) initially committed on May 11, 2018 (v3.3.0-alpha3 ?) fixed this issue
