### ISSUE TITLE
Update to lists in the Slate 0.5x editor

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1161]
Requires #1159 

Here's how I'm thinking the lists should work. The ListStyles class (I believe) should be able to handle all of these use cases (if not we can fix it, or refactor it, or get rid of it with something else - whatever makes the most sense):

* [ ] - Clicking on the bulleted or ordered list buttons on a list with one indent level should completely convert the list to that type (e.g. making a second indent item would maintain the list type)
* [ ] - Clicking on the bulleted or ordered list buttons on a list with more than one indent level should change the type of the selected indent levels only.
* [ ] - Clicking on the style list buttons for a list of the other type (e.g. Clicking on the uppercase letter style for a bulleted list) should perform the changes listed above
* [ ] - Clicking on the style list buttons should set the list type at the selected indent levels only to the selected style

I'll try to show examples in text. I'll use the `|` character to represent a cursor and `[...]` to represent multiple character selection. (For bulleted lists I'll always use the `*` character here out of laziness, but in the actual application it should use the filled circle, hollow circle and square bullets as expected)

## Handling single-indent level lists:

```
* Te|xt
* Text
```

Click on the Numbered List button:

```
1. Te|xt
2. Text
```

Move cursor:

```
1. Text
2. |Text
```

Press tab:

```
1. Text
	a. |Text
```

> Note that the newly indented line is also numeric - that's because the whole list is now numeric.

## Handling multiple-level indent lists:

```
* Text
	* Te|xt
* Text
	* Text
```

Click on the Numbered List button:

```
* Text
	1. Te|xt
* Text
	1. Text
```

> Note that both items at the second indent level have been converted to numeric.

Move cursor to end, hit enter:

```
* Text
	1. Text
	2. |
* Text
	1. Text
```

Hit tab

```
* Text
	1. Text
		* |
* Text
	1. Text
```

> Note that the created item is a bulleted list item, not a numbered list item. That's because the list is still a bulleted list (but a few indent levels have been overridden to be numeric)

## Handling multiple-character selections

```
* Text
	* Te[xt
		* Te]xt
			* Text
```

Click on the Numbered List button

```
* Text
	a. Te[xt
		i. Te]xt
			* Text
```

> Note that the changed items start at `a`, not `1`. `a` is the default for an item at the second indent level for a numbered list.

## Handling clicking on the style buttons

```
* Text
	* Te|xt
		* Text
	* Text
```

Click on the `1.` button

```
* Text
	1. Te|xt
		* Text
	2. Text
```

> Note that, by default, the selected item should be `a.`, but because `1.` was pressed it is set to 1.

Move cursor

```
* Te|xt
	1. Text
		* Text
	2. Text
```

Click on the Numbered List button

```
1. Te|xt
	1. Text
		* Text
	2. Text
```

> Note that there are now two `1.` items. The first item in the list by default is `1.` now that items at indent level 1 have been converted to a numeric list. In addition, the items at indent level 2 are also numeric but have been overridden to use the `1.` style.

Move cursor

```
1. Text
	1. Text
		* Text|
	2. Text
```

Press enter

```
1. Text
	1. Text
		* Text
		* |
	2. Text
```

Press tab

```
1. Text
	1. Text
		* Text
			* |
	2. Text
```

> Note that the newly created item is bulleted. That's because the list is still a bulleted list, just with some numeric overrides.

**Comment by iturgeon** [comment]
I started looking into this - it's going to take some work still. I'm not that experienced w/ slate, spent a few hours looking at it...

I'll leave this here mostly for my own use in the future, but i looks like all the work takes place in list-dropper and the list node converter.

Looking at the docs for list styles https://ucfopen.github.io/Obojobo-Docs/releases/v6.0.1/developers/obo_nodes/indent.html

It looks like dev/9 doesn't editing/saving/converting listStyles correctly.  The rendering in both the viewer and editor look fine, but there's some issue either with the visual editor or the xml conversion that removes the level attribute.

**Comment by zachberry** [comment]
A few more discoveries:

* Clicking on the OL button to turn text into a list works, but clicking the button again doesn't revert the list back to text. My expectation was for the list to revert.
* Selecting multiple lines of text and turning it into a list seems to have additional space between the items - It doesn't seem like it's one list, but doesn't seem like it's three list chunks either:

![2020-04-21 14 01 50](https://user-images.githubusercontent.com/73479/79902875-2da62e80-83e0-11ea-8dae-0233836c87b7.gif)

* The list buttons don't use the pointer cursor like the other toolbar buttons, and don't have the alt text pop overs:

![2020-04-21 14 34 22](https://user-images.githubusercontent.com/73479/79903208-aa390d00-83e0-11ea-8a93-9ccdf0231af8.gif)
