### ISSUE TITLE
Easily be able to move questions in/out of QuestionBanks

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1167]
Real world issue: Instructor created a bunch of questions but then realized they should have been in a QuestionBank - as of now the only way to fix this without re-authoring questions is to drop to XML.

There's also a need to take a practice question, copy it, then paste it inside a QuestionBank to then modify as an assessment question.

Related: #1125 

I'm picturing a menu on QuestionBanks to let you paste in a question you copied (since it's not possible to do this with the normal copy/paste inline). It would also be able to wrap selected questions in a question bank as well as un-wrap a question bank - Much like grouping/ungrouping in a graphic program.

**Comment by qwertynerd97** [comment]
Some potential ideas for copying questions into question-banks (copied from the conversation in Slate to keep it all together):

Option A:
- Create a "Copy JSON" (easy) or a "Copy XML" button in the MoreInfo box for a node
- Create a corresponding "Add from XML/JSON" button at the bottom of each question bank

Option B:
- Create a "Add from Id" button in the question bank that searches the existing nodes for the given id, and then inserts it into the question bank if it is a question or a question bank

Option C:
- Implement drag and drop nodes, and then allow users to drag and drop into questions banks

**Comment by zachberry** [comment]
Talked this over with @iturgeon - what about a possible Option D - In a Question Bank you can click a button to import a question, which then opens a dialog showing you all of the questions you have in your module. Then you can select one, and it'll duplicate it and drop it in the QB.

Later on, we potentially could expand upon that import UI to let you import (for example) questions from edX or Respondus.

I think the dialog would be the easiest option for users. However it's very specific to QuestionBanks where some of your solutions above are more generic. I'm thinking a more generic copy option could then be spun into another issue.

Option A I think is a power-user feature. I'm thinking instead of copy JSON or XML this is where we let them edit the given OboNode as JSON or XML in isolation. That way they can then copy the contents of the RTE, and do what they want with that. Then, if a user pastes in Obo-like XML or JSON in the visual editor it could (maybe, if possible) prompt the user if they want to paste the content in as text or as the OboNode it represents. But again, this could be a separate issue.

Option B I think is too technical for average users, since most IDs will be long UUIDs and those can scare people away.

Option C is absolutely useful. Being able to drag and drop and move around Questions and QuestionBanks inside a QuestionBank is 100% desired. However I see this as a separate issue from copying. I'd also like to implement drag and drop everywhere, so maybe this gets rolled into a more generic Implement-Drag-and-Drop-For-All-Chunks-in-the-Visual-Editor branch.

**Comment by zachberry** [comment]
This is probably the most requested feature I'm getting, got another email today wanting this.

Use cases that we'll want to cover (copied from email):
* Is there a way to copy an existing question and place it in a question bank?
* Is there a way to pull questions from a question bank to use as practice before the assessment?
* Is there a way to move a question bank into an assessment if it has been created outside the assessment page?
