### ISSUE TITLE
Update req.host and iriFactory's host resolution code to use new config.general.hostname

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#117]
<a href="https://github.com/iturgeon"><img src="https://avatars2.githubusercontent.com/u/73480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iturgeon](https://github.com/iturgeon)**
_Friday Feb 16, 2018 at 16:05 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/119_

----

I added general.hostname config to `feature/add-picker` branch.  It'll be easier then trying to pass the host in and resolve it all the time.  Just use a hard coded config var.

**Comment by zachberry** [comment]
I think this config variable got removed somewhere along the line.

@iturgeon Is this still worth pursuing? We would just need to change calls for req.hostname to use the value in the config.

**Comment by iturgeon** [comment]
I think you're right. Closing.
