### ISSUE TITLE
Consider breaking up long module titles

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Obojobo#1172]
Module titles with really long single words in them do this:

![2020-03-03 16 16 39](https://user-images.githubusercontent.com/1275983/75820534-848d7100-5d6a-11ea-91cf-b73878ad84b1.gif)

Long titles also cause issues in the module repository.

**Comment by vutoan1245** [comment]
<img width="396" alt="Screen Shot 2020-03-10 at 12 11 42 PM" src="https://user-images.githubusercontent.com/23706824/76333686-5b1f9880-62c8-11ea-915e-8ec56b2cb226.png">

Same problem in the Dashboard
