### ISSUE TITLE
Triggers dialog can have duplicate keys

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1180]
Related #1169 

To replicate:

1. Create an action button
2. Edit triggers to bring up the triggers dialog
3. Create two duplicate actions (such as 'Start an attempt for')
4. Close the dialog

Result:

```
Warning: Encountered two children with the same key, `assessment:startAttempt`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

**Comment by FrenjaminBanklin** [comment]
@zachberry Would the intention of a fix for this be to prevent duplicate trigger actions, or just to prevent React from complaining about duplicate keys?

The former could be easy to prevent by checking the trigger actions and throwing away duplicates.
The latter could also be easy to prevent by using the actions' array index as part of the keys.

Or potentially preventing both by taking the action name (i.e. 'nav:openExternalLink') and the action value (i.e. {url: 'url/to/external/link'} )then hashing them together, then collapsing duplicates of that?
