### ISSUE TITLE
Missing the (...) details menu for MCChoice elements

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1212]
There's no way to get at these details so you can't set the ID of these without dropping to XML

**Comment by vutoan1245** [comment]
Reason: only nodes that are rendered in the `obojobo-document-engine` have the `...` button (or MoreInfoBox)
Other nodes such as `MCChoice`, `MCFeedback`, `MCAnswer` and a few others are rendered in its parent.
