### ISSUE TITLE
Need an action callout / icon type of chunk

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1220]
We are somewhat doing this with the *Try This!* labels in the editor tutorial, but it would be great to provide this as a chunk type. This is also a common element in online course pages, for example:

* Practice!
* Try This!
* Do this:
* Example
* Hint

etc. We could provide a customizable chunk with a few themes. Here's a mockup of one idea:

![image](https://user-images.githubusercontent.com/73479/77686935-0f314c80-6f74-11ea-8e5f-acd54bde08c2.png)

**Comment by FrenjaminBanklin** [comment]
This could potentially be combined with #1181. Maybe add some 'callout' presets to the Excerpt chunk.
