### ISSUE TITLE
Make A Copy doesn't work as expected

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1221]
Tested on dev/9.

In the visual editor:

* If you make a copy both the original and the copy update their titles to the new title of the copied module

In the XML editor:

* The new document doesn't use the name you input, instead it simply creates a new "My Obojobo Module Title"

**Comment by vutoan1245** [comment]
Similar issue #1129
PR: #1132

**Comment by iturgeon** [comment]
I suggest we move the repository's `router.route('/drafts/:draftId/copy')` route over to obojobo-express and have it do the heavy lifting instead of doing it on the client side.

copy route could use an optional post param for the new title.
