### ISSUE TITLE
Rename File -> Save to File -> "Save Document" in the visual editor

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1228]
This should make things a little more clear that File -> Save is saving everything rather than just the current page.

**Comment by keeeeeegan** [comment]
What are your thoughts on save using "Save Module" instead of "Save Document"? I ask because I noticed "Rename" takes you to a modal that says "Rename Module", and using the same phrasing may make more sense.

**Comment by zachberry** [comment]
@keeeeeegan That makes sense - let's do that!
