### ISSUE TITLE
Make time and ID options for YouTube node more user friendly

### ISSUE THREAD

**Issue by ctcuff** [ucfopen/Obojobo#1234]
Right now, the YouTube Video dialog only supports adding a video through its ID. The start time and end time fields also only support seconds. A better approach would be to allow users to enter the entire video url (so something like `https://www.youtube.com/watch?v=dQw4w9WgXcQ` instead of `dQw4w9WgXcQ`). Same thing applies to the start and end time fields. We should allow times like `1:30` or even `1m30s`.

**Comment by keeeeeegan** [comment]
With my latest commit all of these should work:

`https://www.youtube.com/watch?v=byoEBdVoVpM`
`https://www.youtube.com/watch?v=byoEBdVoVpM&t=152s`
`https://youtu.be/byoEBdVoVpM?t=152`
`https://youtu.be/byoEBdVoVpM`
```<iframe width="560" height="315" src="https://www.youtube.com/embed/byoEBdVoVpM?start=152" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>```

I'm not sure about implementation, but currently what I have is basically the ID field also allows pasting of urls and embed codes, and the id and start time get stripped out.

![Screen Shot 2020-04-10 at 4 55 19 PM](https://user-images.githubusercontent.com/229935/79022536-2e230780-7b4c-11ea-8a0b-5ca80b5bd24b.png)

![Screen Shot 2020-04-10 at 4 55 13 PM](https://user-images.githubusercontent.com/229935/79022538-2ebb9e00-7b4c-11ea-8bef-d64575eb4558.png)

**Comment by ctcuff** [comment]
I like it, seems like the url input should be able to cover a ton of cases now which is nice! I think the only problematic thing now is getting rid of the "in seconds" for the start/end times fields. However, I'm wondering if there's a way to tell the user how to format the time values? Maybe as a placeholder in the input fields?

Like:
```
Start time:
e.x.: 50s, 1:30...
```

Open to other ideas of course.

**Comment by keeeeeegan** [comment]
Oh that's a really good point, I read that in the issue description but hadn't really put it together. Yeah I like that idea, covering a bunch of formats would be awesome, and I think it could be done pretty easily.

Perhaps we have it auto-format the time in a way that we think we'd want to see it (e.g. 4:10), but we also accept other formats and just convert them to appear in that same format?

**Comment by zachberry** [comment]
We could maybe have placeholders in those boxes that indicate the expected formatting, like `(e.g. 112, 112s, 1m, 1:52 or 1m52s)`. Then next to that a (?) component (we have those on the assessment post-attempt pages) that could be clicked on to show all of the accepted formats. Then yeah, I like it converting it to a standard format. I like it storing the data in seconds, but displaying it by default in the `4:10` format.

**Comment by keeeeeegan** [comment]
![Screen Shot 2020-04-16 at 4 17 20 PM](https://user-images.githubusercontent.com/229935/79587914-3aa1e580-80a1-11ea-9619-85384a6fb74f.png)
![Screen Shot 2020-04-16 at 4 17 13 PM](https://user-images.githubusercontent.com/229935/79587918-3bd31280-80a1-11ea-81d3-d7a6ce9f275b.png)

Two mockups implementing the (?) component. I figure we could use a description of what was accepted for the video, as well.

**Comment by ctcuff** [comment]
@keeeeeegan I think `Youtube video URL:` might be a bit clearer for the input but other than that, I really like the mockups!
