### ISSUE TITLE
Hardcode order of items in the insert menu

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1235]
The order of the insert menu is alphabetical but that doesn't lead to a good UX since common items like Text are far to the right, while lesser used items like ActionButton come first:

![image](https://user-images.githubusercontent.com/73479/78268010-a26b0480-74d5-11ea-9093-05d9380b3a8a.png)

I think we should define the order of these things to put common items in front.

**Comment by iturgeon** [comment]
Some options:

* Have each node request a position (sounds sort of terrible)
* Hard code categories (order of them - like `inline text`, `text blocks` `ui`, `media`,  and let each node register itself in one
* Have a configurable override - let the server owner configure the order
* user options - let the user set/store the order themselves as a cusomization

**Comment by zachberry** [comment]
When I was toying with this in the first editor I came up with a configuration file which defined a default order. So then, if your install of obo didn't have Chunk X, Y or Z you could remove that from your config.

I def like user customization. Once we have a ton of chunks this menu won't be workable anymore, and at that point it becomes a favorites menu.

**Comment by zachberry** [comment]
I also see being able to include a horizontal divider in the menu to create logical separations - Text stuff, Question stuff, Media stuff, etc.

**Comment by maufcost** [comment]
Just an idea I had as well:
- We could push the most commonly used chunks to the left, making them more easily accessible (like the text, button, and figure chunks - whatever is more used).
- Then we could automatically adjust their position based on how an author uses them. So, let's say we make the text and button chunks to be on the left by default. If an author decides uses the table chunk, then the next time the author opens the menu, the table chunk would be on the far left. _This is basically a queue ordered on a last-used basis._ This can be kind of flawed since the likelihood of using a table after a table or a button after a button can be pretty low, but can be something to think of :)

**Comment by zachberry** [comment]
> Just an idea I had as well:
> 
> * We could push the most commonly used chunks to the left, making them more easily accessible (like the text, button, and figure chunks - whatever is more used).
> * Then we could automatically adjust their position based on how an author uses them. So, let's say we make the text and button chunks to be on the left by default. If an author decides uses the table chunk, then the next time the author opens the menu, the table chunk would be on the far left. _This is basically a queue ordered on a last-used basis._ This can be kind of flawed since the likelihood of using a table after a table or a button after a button can be pretty low, but can be something to think of :)

Common chunks to the left, I'm thinking the same. As far as moving position based on author use - I like that idea, but I could see that throwing people's muscle memory off if things are shifting around.

**Comment by zachberry** [comment]
I think here's a summary of the discussion so far

* Reorder items so commonly used items on the left
* Separator needed to separate texty stuff from pagey stuff, media stuff, question stuff, etc
* Menu order would be defined (I'm thinking) by a json file - there would be a default one that comes with obo, but you could override with your own 
* In the future, let authors customize this menu. We might have so many chunks that the menu would become too annoying to use, so the list would need to not include all items

Problem with the JSON file, if you have your own custom file and new chunks come out, they won't show up in the menu since you'd have to manually add them. Perhaps not a critical issue, but we could have a wildcard option in the config which would include (alphabetically) any chunks not already added to the list - an overflow essentially.

Last, I think we could get away with _just_ hardcoding the order for now, and add separators later
