### ISSUE TITLE
Cannot duplicate page after editing Assessment

### ISSUE THREAD

**Issue by keeeeeegan** [ucfopen/Obojobo#1255]
While looking into a PR on #1225 I noticed this.

In the editor, click on Assessment on the sidebar. Then, click back to a page. Try to duplicate the page. Some errors will show up in the console and you can no longer close the menu.

**Comment by zachberry** [comment]
Tested on dev/9 and had no issues, tested off of a branch off of dev/10 and can replicate.

**Comment by iturgeon** [comment]
Steps to reproduce: 

1. Click on any the assessment in the editor's nav
2. Click on any page
3. click that page's MoreInfoBox, then duplicate or rename
4. error from obojobo-pages-page/editor-registration.js

This one's kinda ugly, I tried following it back to it's source, but it doesn't make much sense to me.
The model getting sent into getNavItem sometimes doesn't have a parent, but only after clicking on an Assessment.

If you wrap the code attempting to set the label with a try/catch, everything works without a hitch.

**Comment by zachberry** [comment]
I looked into this a little but as well, and wanted to add to what @iturgeon said above.

* Page's editor-registration.js's getNavItem calls `model.parent.children.models.filter` to get the page number (in cases where there's no title).
* Usually this is fine, but if you click on the Assessment section that will load the assessment landing page.
* Now when you click back to the first page's (...) menu, update the title, and then click Done the editor code will rebuild the nav, and each page in OboModel.models will have its getNavItem method called.
* For some reason the assessment landing page that's now loaded has no parent.

An easy fix is to simply change the Page editor-registration getNavMethod to check if its an orphan (`model.isOrphan()`), and if it is, abort attempting to grab the page number. And truthfully any pages in the assessment section won't have any impact on the nav. IF, in the editor, it's expected that the assessment landing page doesn't have a parent then this would be the way to go. However I bring it up in case this is another bug. Should the assessment landing page have a parent model?
