### ISSUE TITLE
Editor UI polish

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1258]
Now with #1159 in place the editor has started to solidify and we can take some time to polish a few nitpicky UI things. Here's my recommendations for things to touch up. A lot of these are things I didn't notice during development but have noticed as we move ahead:

* Icon in the tool bar for inline math (currently "f(x)") should match the icon we're using for the Math Equation chunk.

<img width="766" alt="Screen Shot 2020-04-08 at 5 32 19 PM" src="https://user-images.githubusercontent.com/73479/78836855-ea4fc700-79c0-11ea-8c02-8afd5dde3a3f.png">

* Toolbar needs vertical separators to logically separate different types of actions. Current thought is `Headings` | `B I S` | `Quote Code Math` | `Link` | `Sup Sub` | `Left Center Right` | `Indent Unindent` | `Hanging` | `BulletList NumberedList`

<img width="1028" alt="Screen Shot 2020-04-08 at 5 51 59 PM" src="https://user-images.githubusercontent.com/73479/78837271-af01c800-79c1-11ea-928e-e9425f713943.png">

* The square insert-chunk menu awkwardly sits touching the circular (+) menu. Ideally both of these menus could look connected instead of sitting next to one another (which may mean changing the color of the insert-chunk menu from gray to white):

<img width="136" alt="Screen Shot 2020-04-08 at 5 39 02 PM" src="https://user-images.githubusercontent.com/73479/78837450-1881d680-79c2-11ea-9346-0e3bf1f4e3bc.png">

* Id field and the Copy ID button should sit flush together. The rounded radiuses where they connect should be removed:

<img width="92" alt="Screen Shot 2020-04-08 at 5 39 53 PM" src="https://user-images.githubusercontent.com/73479/78837498-37806880-79c2-11ea-843c-169254a08a4d.png">

* In the details menu the delete button should float far right, separate from the regular purple commands
* The details menu should be set at a specific rem value rather than em. Currently the details menu for pages is at a good size, but the details menu for chunks in a page looks to be too large.

![image](https://user-images.githubusercontent.com/73479/78837567-5a128180-79c2-11ea-81bb-e82442fd5aab.png)

* In the triggers dialog some of the input fields look 3d which don't match the flat look of the rest of the app:

<img width="478" alt="Screen Shot 2020-04-08 at 5 40 26 PM" src="https://user-images.githubusercontent.com/73479/78837656-88905c80-79c2-11ea-8d90-1dd49aaa9a95.png">

* The File / Edit / etc menus need horizontal separators to logically divide commands:

<img width="259" alt="Screen Shot 2020-04-08 at 5 40 43 PM" src="https://user-images.githubusercontent.com/73479/78837727-a8c01b80-79c2-11ea-8637-fc54a247ccf0.png">

* In the IFrame properties window these two inputs are too close togther:

<img width="569" alt="Screen Shot 2020-04-08 at 5 40 59 PM" src="https://user-images.githubusercontent.com/73479/78837752-b4abdd80-79c2-11ea-9e8c-a5bd22ebeb28.png">

* Also, the input shown here feels too close to the on/off switches that come after:

<img width="508" alt="Screen Shot 2020-04-08 at 5 41 08 PM" src="https://user-images.githubusercontent.com/73479/78837783-c7bead80-79c2-11ea-83ac-63bbbcb9e7ba.png">

* The blank YouTube state is too sparse and should be using $font-default (Libre Franklin). Perhaps a large muted video icon or YT icon should be shown inside the box as a clear placeholder.

<img width="845" alt="Screen Shot 2020-04-08 at 5 41 24 PM" src="https://user-images.githubusercontent.com/73479/78837834-ede44d80-79c2-11ea-91d3-7ca684528d7b.png">

* The table edit menu is using the default system button font instead of $font-default. The up/down arrow button has a different feel then the flat look of the rest of the app:

<img width="227" alt="Screen Shot 2020-04-08 at 5 42 34 PM" src="https://user-images.githubusercontent.com/73479/78837862-fc326980-79c2-11ea-9280-9fe486a25072.png">

* The assessment page doesn't explain what the different portions of the page do. Currently it's Landing Page, then Assessment QB, then the various post-assessment landing pages (which we call Score Actions), then finally the grading rubric. I would like to more clearly separate each of these and ideally have some text explaining what they do. Additionally, in the visual editor would like to rename 'Score Actions'. Finally, the edit button to change the range for a score action needs updating. (All of this may need to be pulled into its own issue):

<img width="489" alt="Screen Shot 2020-04-08 at 5 43 48 PM" src="https://user-images.githubusercontent.com/73479/78838085-62b78780-79c3-11ea-824b-87f4f8d6b909.png">

<img width="1043" alt="Screen Shot 2020-04-08 at 5 44 36 PM" src="https://user-images.githubusercontent.com/73479/78838171-972b4380-79c3-11ea-9fb3-ea7daf92f280.png">

* The buttons that show up at the end of questions and question banks feel disorganized and too similar. Perhaps some alternate styles, icons, or moving their positions may make this clearer. We may need to develop a button color for the editor that looks different from the ActionButton chunk which a student might click on:

<img width="994" alt="Screen Shot 2020-04-08 at 5 44 28 PM" src="https://user-images.githubusercontent.com/73479/78838159-91356280-79c3-11ea-9e29-904daeffb65e.png">

* The assessment rubric feels like it doesn't contain enough whitespace and feels cramped. The radio buttons also don't look vertically aligned with the text they correspond to. The UI is in a purple/pink box as well which is a different look from the rest of the application (open to ideas on how to handle this, none at the moment). Finally, it seems to somehow still be content editable since Chrome is showing a spelling mistake on 'gradebook':

<img width="923" alt="Screen Shot 2020-04-08 at 5 44 57 PM" src="https://user-images.githubusercontent.com/73479/78838312-e40f1a00-79c3-11ea-9c24-843afd805e66.png">

<img width="905" alt="Screen Shot 2020-04-08 at 5 45 06 PM" src="https://user-images.githubusercontent.com/73479/78838353-ff7a2500-79c3-11ea-943a-e3481b7547e1.png">

The extra credit mod page % symbol is too close to the input box. The Add Mod button could use some additional spacing from the surrounding area. Finally, it's a bit fiddily to know when $last_attempt will show up - would also prefer a label like "The Last Attempt" over the more technical variable you would use in XML/JSON:

<img width="987" alt="Screen Shot 2020-04-08 at 5 45 20 PM" src="https://user-images.githubusercontent.com/73479/78838497-4ff18280-79c4-11ea-9c39-1c3acbcf0560.png">

**Comment by keeeeeegan** [comment]
In my youtube branch I was thinking of changing up the default text when adding a youtube video. 

![Screen Shot 2020-04-09 at 2 42 36 PM](https://user-images.githubusercontent.com/229935/78929463-70771680-7a70-11ea-82b8-ad1b02be0ef8.png)

**Comment by ctcuff** [comment]
@keeeeeegan I like it!

**Comment by keeeeeegan** [comment]
@ctcuff Thanks!

**Comment by keeeeeegan** [comment]
I kind of feel silly after mocking up the toolbar update because it was pretty self-explanatory, but...

![Screen Shot 2020-04-15 at 2 20 36 PM](https://user-images.githubusercontent.com/229935/79374013-13bea480-7f25-11ea-99da-867a0fce01cf.png)

**Comment by zachberry** [comment]
@keeeeeegan Looks sweet! Only thing is I think we should have a divider between the link and the sub/sups

**Comment by keeeeeegan** [comment]
Oops, missed that one!

**Comment by keeeeeegan** [comment]
Ok so some of these are mockups/comps, and others are ideas (as I am still not sure of the solution):

![file-menu copy](https://user-images.githubusercontent.com/229935/80760428-e407c300-8b06-11ea-812b-013be8a51144.png)
![top-menu-edit-menu](https://user-images.githubusercontent.com/229935/80760576-1b766f80-8b07-11ea-9fc9-7afa5492b409.png)
Mockups for file menu with lines. I looked at Google Docs for inspiration.

![iframe](https://user-images.githubusercontent.com/229935/80760475-f681fc80-8b06-11ea-856b-9b2a9411f64e.png)
This one just needs padding updates. I decided not to make comps for all of the padding ones, as it would be easier to adjust in css.

![table-edit-menu](https://user-images.githubusercontent.com/229935/80760513-0699dc00-8b07-11ea-9108-46c0f20315b0.png)
I basically mocked up the table edit menu to just match more closely the rest of the UI.

![top-menu](https://user-images.githubusercontent.com/229935/80760597-23ceaa80-8b07-11ea-8d5b-7f0cc87131d4.png)
Mockup for updated top bar, with lines.

![youtube](https://user-images.githubusercontent.com/229935/80760636-32b55d00-8b07-11ea-83f4-8faf8eac3d0d.png)
Updated Youtube placeholder that includes an icon.

![buttons-assessment-feedback](https://user-images.githubusercontent.com/229935/80760183-7d82a500-8b06-11ea-86dc-db4b712d8c47.png)
For assessment feedback, centering the buttons seemed to fix part of the layout weirdness. I was also wondering what if we changed the "Add Feedback" button to instead be a thinner version of the full thing. When clicked, it would expand to the full textarea.

![attempt-bar](https://user-images.githubusercontent.com/229935/80760336-b91d6f00-8b06-11ea-9966-2016058f188d.png)
For the attempt bar, I was thinking it may be useful to show both the total points as well as the fact that it's the "total possible." If the slider is pushed to the end, the checkbox would check. Alternatively, if the checkbox is checked, the slider would jump to the end.

I'm still working on the insert chunk mockup, though I imagine we'd just want to match the border weight and have it connect to the round edge. For the score range edit icon, were you thinking of keeping it as an icon or switching it to be a button?
