### ISSUE TITLE
Edit menu for left or right aligned equation chunks are kinda strange

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#1259]
When a math equation chunk is not center aligned, the edit menu is still center aligned, so it pops up in an unexpected location.

My first ideas:

A. Adding a container around the whole chunk when clicked - then centered edit menu isn't so strange
B. Move the edit menu to left or right align along with the alignment of the chunk

<img width="834" alt="Screen Shot 2020-04-10 at 3 17 11 PM" src="https://user-images.githubusercontent.com/73480/79017091-818e5900-7b3e-11ea-96f0-78323c9733c0.png">

**Comment by zachberry** [comment]
I'd prefer to left or right align it over the box

**Comment by keeeeeegan** [comment]
I agree with moving it to the box (B)
