### ISSUE TITLE
New user logins seem to sometimes fail the first time

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#126]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Thursday Mar 15, 2018 at 20:48 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/128_

----

Might be the very first user on a totally clean db

**Comment by zachberry** [comment]
This still seems to be happening on master and dev/5b

**Comment by iturgeon** [comment]
I'm pretty sure I fixed this on dev/6
