### ISSUE TITLE
getNavItem throws error after clicking on assessment (dev/10)

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#1266]
1. Click on any the assessment in the editor's nav
2. Click on any page
3. click that page's MoreInfoBox, then  duplicate or rename 
4. error from `obojobo-pages-page/editor-registration.js`

This one's kinda ugly, I tried following it back to it's source, but it doesn't make much sense to me.
The model getting sent into getNavItem sometimes doesn't have a parent, but only after clicking on an Assessment.

If you wrap the code attempting to set the label with a try/catch, everything works without a hitch.

**Comment by ctcuff** [comment]
I think #1255 is similar to this too

**Comment by iturgeon** [comment]
Oh nice eye, closing as a duplicate
