### ISSUE TITLE
Dev/10 editor - Can't undo creating/deleting pages

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1269]
It seems the undo/redo stack doesn't include creating/deleting pages or sections

**Comment by FrenjaminBanklin** [comment]
Looks like it'll also just play whichever action was done/undone over whichever page is currently active, as well.

e.g. add a button on page 1, undo it, select page 2, redo it, button is added to page 2 instead of page 1.

**Comment by qwertynerd97** [comment]
Creating pages is not actually done through the Slate editor, so it does not get added to slates undo/redo stack.  
The replay on the wrong page could probably be fixed by clearing the redo/undo stack when swapping pages.
