### ISSUE TITLE
Paste and Match Style results in Insert menu text showing up in the Editor

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1282]
This is a weird one, but if you use paste and match style with a selection containing text, a list and more text you get the text of the insert menu for some reason:

![2020-04-23 18 40 54](https://user-images.githubusercontent.com/73479/80156748-abaa3700-8592-11ea-85cc-75142fece798.gif)

**Comment by vutoan1245** [comment]
Tested on dev/10-emerald. Looks like this is no longer a problem.
