### ISSUE TITLE
Complete editor UI for Numeric Questions

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1299]
This is for the #1298 branch (issue/554**b**)

A rough overview of what needs to be done:

- [x] * Review the editor UI for Numeric Assessment questions
- [x] * I'm concerned the way I implemented the code is needlessly complicated, need to review the new editor code for Question, NumericAssessment, NumericChoice, NumericAnswer and NumericFeedback. Very open to changes.
- [x] * Question normalization was disabled to get things functioning, so this should be restored
- [x] * Not sure if I need both NumericChoice and NumericAnswer. Also, some of the new chunks simply use copied code from MCChoice, MCAnswer or MCFeedback (such as converter code). Want to pull out duplicated code into a common library.
- [x] * onSetAssessmentType is dumb, it simply sets the node to the expected structure for NumericAssessment, but that structure shouldn't be hardcoded there.
- [x] * Remove any old schema.js files

**Comment by qwertynerd97** [comment]
Major bugs found to fix:
- [ ] Numerics load up with no answer choices
- [ ] Numerics start with a blank text node
- [ ] Saving a numeric with no choices crashes the editor on reload
- [ ] Add solution is not centered
- [ ] Disable survey button
