### ISSUE TITLE
Changing the name of a module in the Visual Editor can revert the document to an older state

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1330]
Here are the steps:

1. Take the XML of a non-trivial document (I was unable to replicate with a very basic document, I'm not sure what the deciding factor is)
2. In a new empty module, edit the XML and paste the XML you copied from step 1. Save - you should notice that the title changes.
3. Change to editing in the Visual Editor, then rename the module and click away to save

Result: The contents of the module revert to back before you overwrote the document with the copied XML.

**Comment by iturgeon** [comment]
Confirmed, happens with the JSON editor too.
