### ISSUE TITLE
Make Obojobo content item selection responses LTI 1.0 compliant

### ISSUE THREAD

**Issue by adrianfish** [ucfopen/Obojobo#1346]
Currently, as of code in master, Obojobo does not sign the content item link response message. v1.0 does have a clause about not needing to sign the response message, but to not do so is less secure and may well make Obojobo not play well with LMSs other than Canvas.

From the LTI v1.0 spec:

"The response message must be signed unless the initial request included an accept_unsigned parameter with a value of true. Otherwise the TP may choose whether to sign the response message, or not."

**Comment by iturgeon** [comment]
We've definitely been driven entirely by what Instructure's Canvas requires so far.  Agree it would be good to have that message signed.  

@adrianfish do you know of any LMS's that require the signed response?

For future reference, examples can be seen in section 3.2 here https://www.imsglobal.org/specs/lticiv1p0/specification
