### ISSUE TITLE
9.1.0 Review: Link menu buttons rendering strangely

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1357]
Seems the buttons are positioned low or something, but the bottom line of the menu has white gaps due to the buttons:

![Screen Shot 2020-06-01 at 9 56 52 AM](https://user-images.githubusercontent.com/73479/83416263-6af1d900-a3ee-11ea-8abd-f374add8bc14.png)

**Comment by iturgeon** [comment]
Seems the icons have a background / background color inherited from button.

Will probably need `background-color: transparent` with a specificity to target just these buttons
