### ISSUE TITLE
New Feature - Custom email receipt 

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#1394]
This idea comes from the UCF Libraries - It'd be nice to be able to send an email with links to resources the learner could use at a later time.

Perhaps we could re-implement Obojobo Classic's completion score receipt w/ a customizable section where the author could place content?

Email markup is really fiddly, so we'd have to limit the formatting a lot. Also have to be really cautious about this possibly opening up fishing attacks or tracking pixels (though maybe the second has a use case).

**Comment by zachberry** [comment]
Related: #244
