### ISSUE TITLE
Question Bank editor pick input not validating input

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1398]
I'm not sure if this is a regression, because I want to say this may have been fixed in an earlier release. But the Question Bank "pick" input box in the visual editor allows values like (-16, 6.2 or 'eeee').

Need to (on blur) enforce:
* [ ] a positive integer value,
* [ ] a min of 1

 It may be worth looking back to dev/9 or dev/10 just to make sure this wasn't already fixed.

**Comment by ctcuff** [comment]
Looks like this was fixed in dev/12, tested and I couldn't replicate. This happens in dev/9 - dev/11 though.
