### ISSUE TITLE
Visual editor in the version history menu is partially usable

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Obojobo#1401]
The visual editor that appears in the version history is partially usable. Action button triggers are changeable, menus are openable, new pages can be added, etc.

Any modifications made to the page in this scaled down version of the editor are actually saved, but it throws various errors. The editor should probably have a 'read-only' mode to account for its use in the version history.

**Comment by ctcuff** [comment]
Without making any edits to the editor itself, a quick & dirty fix could be to just set `pointer-events: none;` on the iframe in the menu. You wouldn't be able to select/click buttons or highlight text but you'd still be able to scroll and view content.
