### ISSUE TITLE
Prevent attempt resuming on 3.3.0 since we won't have it ready in time

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#144]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Mar 30, 2018 at 19:32 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/146_

----

I'm not 100% sure what the status is on attempt resuming but I had started working on implementing it. However we're not going to have it ready in time so I'm making this issue as a reminder to tie up any loose ends for now.

**Comment by zachberry** [comment]
Closing in favor of #529
