### ISSUE TITLE
Splitting a Figure caption produces multiple lines of text when that text is formatted

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1483]
Best shown in an example:

![2020-08-21 14 12 39](https://user-images.githubusercontent.com/73479/90924738-00818100-e3be-11ea-99fd-d2c57124ec8f.gif)

My expectation is that the caption text that got converted into regular text would remain one line. I suspect there is code in Text chunk's normalization methods that is doing this.

**Comment by maufcost** [comment]
Just found out another issue that I believe can be within this thread. When you type "return" when your text cursor is right behind the styled text, the figure disappears. 
![obo](https://user-images.githubusercontent.com/39862359/93892259-577abe80-fcba-11ea-9180-95da671ce9c2.gif)
