### ISSUE TITLE
Fix broken/skipped 'inserts event' test in events.test.js

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#15]
<a href="https://github.com/SidTheEngineer"><img src="https://avatars0.githubusercontent.com/u/19176417?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SidTheEngineer](https://github.com/SidTheEngineer)**
_Friday Jul 28, 2017 at 17:56 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/16_

----

For now, the test that covers inserting an event in `events.test.js` is skipped, so that we can finish building out the caliper stuff. After we've gotten things up and running, we'll need to fix/rewrite this test

**Comment by zachberry** [comment]
I believe this is an old issue that's since been resolved with #236
