### ISSUE TITLE
MoreInfoBox form can break

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1514]
This happens in Safari, however I have seen some of this behavior in Chrome:

![image](https://user-images.githubusercontent.com/73479/92947074-89239800-f425-11ea-9b77-13e60144c292.png)

**Comment by maufcost** [comment]
Tested on Chrome and Safari, and I believe this issue has also already been fixed as well.

![obo](https://user-images.githubusercontent.com/39862359/131878426-1cb51fb0-9178-4676-9247-9cbcef62d1fd.gif)
