### ISSUE TITLE
Triple clicking to select the entirety of a line and then typing jumps the selection to the next node

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1550]
Best shown here:

![2020-09-30 15 41 57](https://user-images.githubusercontent.com/73479/94731952-96041f00-0333-11eb-86a0-8501410d6fbe.gif)

We've had issues with this before with Slate - it could still be a slate issue or perhaps something to do with breakToText?

**Comment by vutoan1245** [comment]
Can confirm it is a Slate issue.
![triple-click](https://user-images.githubusercontent.com/23706824/95126908-291ec980-0725-11eb-926a-8a70ae2327e4.gif)

Reason: triple-click selects the current node and the beginning of the node below it
