### ISSUE TITLE
Editor doesn't handle upload too large error

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#1634]
The 413 error returned by nginx when the 'request entity too large' isn't gracefully handled by the editor (it just eats the error).  The editor is expecting a json body and is getting nginx's standard error page instead.

```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0</center>
</body>
</html>
```

**Comment by maufcost** [comment]
I believe this issue can be closed. #1900 has been merged already :)
