### ISSUE TITLE
Research using ORY editor

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#164]
<a href="https://github.com/iturgeon"><img src="https://avatars2.githubusercontent.com/u/73480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iturgeon](https://github.com/iturgeon)**
_Wednesday Apr 18, 2018 at 20:04 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/166_

----

This may give us a huge head start on the Editor : https://github.com/ory/editor

**Comment by zachberry** [comment]
Closing as I'm assuming the list above is outdated (@qwertynerd97 can you confirm?)
