### ISSUE TITLE
Objectives

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1644]
The desire is to tie a page and/or questions to one or more Module-level objectives.

Some initial ideas in an example XML mockup:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ObojoboDraftDoc>
	<Module title="edX Multiple Choice Question Example">
		<objectives>
			<objective id="644a1848-39bc-4629-8773-3a047eaa2aae">Students will be able to categorize types of animals into the correct classes with a graphic organizer after reading an article on animal traits.</objective>
			<objective id="26b03cca-945f-4b8c-9d15-1b64b882a284">By working in collaborative literature groups, students will be able to form predictions about the next chapter of Anne of Green Gables using at least three pieces of textual evidence.</objective>
		</objectives>
		<Content>
			<Page objective="26b03cca-945f-4b8c-9d15-1b64b882a284">
				<Question>
					<p>test</p>
					<MCAssessment responseType="pick-one">
						<MCChoice score="100">
							<MCAnswer>
								<p>Correct</p>
							</MCAnswer>
							<MCFeedback>
								<p>Correct</p>
							</MCFeedback>
						</MCChoice>
						<MCChoice score="0">
							<MCAnswer>
								<p>Incorrect</p>
							</MCAnswer>
						</MCChoice>
					</MCAssessment>
					<solution>
						<Page>
							<p>This is a description of the solution to the problem.</p>
						</Page>
					</solution>
				</Question>
				<Question objective="644a1848-39bc-4629-8773-3a047eaa2aae">
					<p>test</p>
					<MCAssessment responseType="pick-one">
						<MCChoice score="100">
							<MCAnswer>
								<p>Correct</p>
							</MCAnswer>
							<MCFeedback>
								<p>Correct</p>
							</MCFeedback>
						</MCChoice>
						<MCChoice score="0">
							<MCAnswer>
								<p>Incorrect</p>
							</MCAnswer>
						</MCChoice>
					</MCAssessment>
					<solution>
						<Page>
							<p>This is a description of the solution to the problem.</p>
						</Page>
					</solution>
				</Question>
			</Page>
		</Content>
	</Module>
</ObojoboDraftDoc>
```

My current thoughts:

* Objectives are plain-text only, which makes it technically easier to handle and keeps them simplified
* Objectives are defined only at the Module level. Each objective is given an id (UUID by default).
* All OboNodes can define an `objective` attribute which refers to one of the Objective IDs. These would create an "objective context" which would include itself and its children. For example, if a Page is set to objective `A` then all of the OboNodes within that page are considered to be related to objective `A`.
* The exception to the rule above is that if an OboNode defines an objective it does not adopt any objectives from its parent and starts a new objective context. Therefore, in this example:

```xml
<Page objectives="a">
  <Question id="q1" />
  <Question id="q2" objectives="b" />
  <QuestionBank objectives="c">
    <Question id="q3">
    <Question id="q4" objectives="b">
  <QuestionBank>
</Page>
```

* `q1` has objective `a`
* `q2` has objective `b`
* `q3` has objective `c`
* `q4` has objective `b`

Open to discussion, but my thoughts are this allows for a few use cases:

1. Simply define objectives to pages, and any practice questions within can be easily lumped into covering the same objective. This would be ideal since pages would be logically divided into topics/objectives and all content within relates to the same topic/objective.
2. Simply define objectives to questions. Then there is no structure enforced on pages, which could simply be a logical grouping of content that doesn't conform to one page per objective. Then questions can be granularly defined to be tied to an objective and can differ even on the same page.
3. Define objectives to pages but allow questions to define their own objectives, allowing an author to mostly conform to use case 1, but making allowances for putting questions covering a different objective wherever it makes sense logically or for the sake of flow

**Comment by zachberry** [comment]
Here are some first draft mockups of what the UI might look like:

Module's more details menu, now has an 'Objectives' option:

![Screen Shot 2021-01-12 at 2 07 30 PM](https://user-images.githubusercontent.com/73479/104360951-cedd9380-54df-11eb-96ae-ec9ba7d9cc6e.png)

> Objectives would be labelled as `A`, `B`, and so on as a quick way to scan which objective applies where

Clicking on the Edit button would open the Objectives Dialog (Similar in design to the Triggers/Actions dialog):

![Screen Shot 2021-01-12 at 2 08 16 PM](https://user-images.githubusercontent.com/73479/104361441-73f86c00-54e0-11eb-8648-4c713cfac85b.png)

> Here the second objective, B, is being edited, which happens when the user clicks anywhere on the text of an objective. Clicking on the Done button or clicking off of the objective currently being edited stops editing that objective.

As much as possible I'd like to hide away the objective ID from the user as this is more of a technical requirement and users using the WYSIWYG editor don't need to worry about ids. However users (imo) should still be able to edit these values in the WYSIWYG editor (perhaps changing the IDs to match their own schema), so as a compromise the ID is hidden behind an 'Edit Objective ID' button shown above. When clicked on the objective ID is shown in an editable field (as long as the objective is currently being edited):

![Screen Shot 2021-01-12 at 2 08 31 PM](https://user-images.githubusercontent.com/73479/104361900-187aae00-54e1-11eb-96e7-f2703b78c19d.png)

Questions more details menu now has an 'Objective' option, with a drop down to select either no objective or one of the objectives defined. (Pages would get the same option as well)

![Screen Shot 2021-01-12 at 2 07 41 PM](https://user-images.githubusercontent.com/73479/104361125-0ba98a80-54e0-11eb-9995-3a135e39dc1e.png)

Here you can see what the combobox might look like when opened:

![Screen Shot 2021-01-12 at 2 07 58 PM](https://user-images.githubusercontent.com/73479/104361161-18c67980-54e0-11eb-8a16-ba82f003daf7.png)

> Selecting the last option, `(Edit objectives...)` is a special shortcut which would open the Module-level Objectives dialog.

In the case where the underlying JSON includes a reference to an objective ID that is not defined in the module we would have a special option in the combobox showing that we couldn't find that objective:

![Screen Shot 2021-01-12 at 2 07 50 PM](https://user-images.githubusercontent.com/73479/104361355-54f9da00-54e0-11eb-9a53-292a39fa287b.png)

> If the user selects another option from the combo box then the `Unknown objective` option would disappear

**Comment by zachberry** [comment]
Some ideas for how we'd handle multiple objectives (Either we want to do this right away, or postpone for a future update)

We'd change the XML attribute to `objectives` which would take a comma-separated list of objective IDs. Such as

```xml
<Question objectives="644a1848-39bc-4629-8773-3a047eaa2aae,26b03cca-945f-4b8c-9d15-1b64b882a284" ... >
```

In the UI, the combo-box would became a custom control that allows a user to select multiple objectives. When collapsed this control would look like a combo-box:

![image](https://user-images.githubusercontent.com/73479/105085132-55a4ea00-5a65-11eb-8bd5-0012cd046268.png)

That would expand to this state when clicked on:

![image](https://user-images.githubusercontent.com/73479/105085187-66556000-5a65-11eb-94d8-2d7f20bad66d.png)

> Clicking somewhere off of the new box (including the Done button or somewhere else in the document) would close it

The collapsed state when there are multiple objectives would simply be a list of objectives (The text of the objective is not displayed here)

![image](https://user-images.githubusercontent.com/73479/105085301-8e44c380-5a65-11eb-9126-535cc8040401.png)

Finally, expanding the objective box when no objectives exist might look like this:

![image](https://user-images.githubusercontent.com/73479/105085345-9e5ca300-5a65-11eb-8d04-902c0b4e71ed.png)

**Comment by zachberry** [comment]
Based on a recent conversation there is a desire to be able to customize the labels (i.e. instead of `A`, `B`, etc there is a need for `1.0`, `1.1`, `2.0`, etc. Additionally, there's desire in the future to be able to use objectives from other modules (or in other words, objectives would exist between modules). Therefore we're going to stick with UUIDs, which would translate nicely in the future when we create an objectives table.

Additionally, we are going to move ahead with supporting multiple objectives. Here's a mockup of that data with labels and multiple objectives:

```xml
<?xml version="1.0" encoding="utf-8"?>
<ObojoboDraftDoc>
  <Module>
    <objectives>
      <objective id="644a1848-39bc-4629-8773-3a047eaa2aae" label="1.0">Students will be able to categorize types of animals into the correct classes with a graphic organizer after reading an article on animal traits.</objective>
      <objective id="26b03cca-945f-4b8c-9d15-1b64b882a284" label="1.1">By working in collaborative literature groups, students will be able to form predictions about the next chapter of Anne of Green Gables using at least three pieces of textual evidence.</objective>
    </objectives>
    <Content>
      <Page objectives="26b03cca-945f-4b8c-9d15-1b64b882a284">
        <Question>
          ...
        </Question>
        <Question objectives="644a1848-39bc-4629-8773-3a047eaa2aae">
          ...
        </Question>
      </Page>
      <Page objectives="644a1848-39bc-4629-8773-3a047eaa2aae,26b03cca-945f-4b8c-9d15-1b64b882a284">
        ...
      </Page>
    </Content>
  </Module>
</ObojoboDraftDoc>
```

**Comment by zachberry** [comment]
Had a discussion with @iturgeon on how we could handle modules sharing objectives.

Keeping objectives local to the document is useful since the document itself has everything necessary. If objectives were moved to a database table that would mean the objective wouldn't exist when you downloaded the document.

We decided it would be best to link objectives - which probably would happen in the module tree (not yet developed). This would simply say that Module A, Objective X is "linked" to Module B, Objective Y. The text of the two objectives could be different, but the system would maintain a philosophical link between the two.

It would be helpful as an author to be able to import an objective. This could happen inside the module tree - When adding an objective you could find any other objective from the latest versions of other modules inside your module tree.

**Comment by zachberry** [comment]
Based on the changes of allowing you to edit the label of objectives, here's some tweaked UI mockups.

Now each objective is (by default) labeled 'Objective ${letter}'. In this mockup Objective B is currently being edited:

![image](https://user-images.githubusercontent.com/73479/108730760-d8541580-74f9-11eb-9b4f-4a0e54029d42.png)

When the user mouses over the title of an objective it shows a gray rectangle around it, indicating it can be edited:

![image](https://user-images.githubusercontent.com/73479/108730845-ed30a900-74f9-11eb-8fd8-29d090ce6150.png)

Clicking on the title would then show a input box allowing you to edit the objective label (Note that "Objective" is not user editable)

![image](https://user-images.githubusercontent.com/73479/108730963-0fc2c200-74fa-11eb-9518-b53a8b7052e1.png)

Newly created objectives will always follow the A, B, C... scheme. So if a user has customized their objective labels like this:

1. Objective A
2. Objective 1.1
3. Objective D

Then if a new objective is created it would be the fourth objective (D), and would result in

1. Objective A
2. Objective 1.1
3. Objective D
4. Objective D

Having two objectives with the same label is undesired, but I'm thinking we rather leave this to the user to correct rather than try to anticipate fixes or code around the issue.

**Comment by paradisojr** [comment]
> It would be helpful as an author to be able to import an objective. This could happen inside the module tree - When adding an objective you could find any other objective from the latest versions of other modules inside your module tree.

...and it would be super cool if within this 'module tree' each objective had nested values (Unit 1: Question 1, Unit 1: video, et al.) that could expand to show what items are currently aligned with that objective. This would come in very handy when trying to estimate a rough value for whether or not a given objective has enough quantitative evidence to power a system recommendation or populate a dashboard with any level of accuracy. For example, and objective with 1 piece of evidence, would likely not be given the same weight (or have the same statistical 'power') as one with 12 pieces of evidence, etc.

**Comment by Surapanirakesh** [comment]
Screenshots for recent changes and Mockups of UI,
Objective Library
<img width="780" alt="Screen Shot 2021-08-09 at 4 55 10 PM" src="https://user-images.githubusercontent.com/43663588/128894980-c3f2b3fb-baeb-4343-8e6e-185181f29e77.png">

Objective, when we click on Create Objective
<img width="698" alt="Screen Shot 2021-08-09 at 4 55 32 PM" src="https://user-images.githubusercontent.com/43663588/128895036-09a9c559-afb1-4b36-b6ca-cc4847a98656.png">

Selected Objectives Display in More info Box
<img width="467" alt="Screen Shot 2021-08-09 at 4 57 26 PM" src="https://user-images.githubusercontent.com/43663588/128895136-ce6de698-0d95-44bf-b398-fb58550d19e7.png">

Deleting an objective
<img width="831" alt="Screen Shot 2021-08-09 at 10 20 01 AM" src="https://user-images.githubusercontent.com/43663588/128895279-84d41e54-06a8-4db8-bc93-1f746b842c72.png">

**Comment by zachberry** [comment]
Here's my suggested changes (original image followed by new mockup):

Objective Library
<img width="780" alt="Screen Shot 2021-08-09 at 4 55 10 PM" src="https://user-images.githubusercontent.com/43663588/128894980-c3f2b3fb-baeb-4343-8e6e-185181f29e77.png">
<img width="783" alt="Screen Shot 2021-08-11 at 5 50 17 PM" src="https://user-images.githubusercontent.com/73479/129108299-75da55fb-9863-4adb-9370-f5f9cf41da3e.png">
* "Select objective, Edit, Delete" heading removed
* Add text: "Select one or more objectives that apply to this item"
* Round the corners of the items in the list, reduce border strength
* Replace pencil icon with Edit link button
* Replace X icon with the look used elsewhere in the system (I believe there's a DeleteButton component)
* Font for the label should be $font-monospace (Roboto Mono)
* Ensure the objective text is at the same horizontal position for every item in the list
* Change Create Objective button to "+ Create New Objective"
* Remove Add/Cancel buttons and replace with Done (I'm worried cancel may be confusing if they happen to create a new objective, since I assume that wouldn't be cancelled, and if the user does make a mistake fixing it would be easy). Vertically center Done button so that it sits centered between the bottom of the dialog and the bottom of the gray box.
* Selected items should have a blue selected background (There might be a defined color for this somewhere in _includes.scss)

Objective, when we click on Create Objective
<img width="698" alt="Screen Shot 2021-08-09 at 4 55 32 PM" src="https://user-images.githubusercontent.com/43663588/128895036-09a9c559-afb1-4b36-b6ca-cc4847a98656.png">
<img width="701" alt="Screen Shot 2021-08-11 at 5 33 38 PM" src="https://user-images.githubusercontent.com/73479/129108802-71b1a4ad-f0d8-43af-b206-9a92e95dbd45.png">

* Retitle as "Create New Objective"
* Change font of label input to $font-monospace
* Change font of objective input to $font-default (Libre Franklin)
* Give more whitespace between the input labels and the inputs

Selected Objectives Display in More info Box
<img width="467" alt="Screen Shot 2021-08-09 at 4 57 26 PM" src="https://user-images.githubusercontent.com/43663588/128895136-ce6de698-0d95-44bf-b398-fb58550d19e7.png">
<img width="464" alt="Screen Shot 2021-08-11 at 5 28 56 PM" src="https://user-images.githubusercontent.com/73479/129108966-cd9ceaa2-a32e-4312-b693-8c6045010e49.png">

* Turn into a bulleted list
* Labels should use $font-monospace
* Ensure that the horizontal position of objectives always start at the same place
* Move edit button to the top of the Objectives section

Deleting an objective
<img width="831" alt="Screen Shot 2021-08-09 at 10 20 01 AM" src="https://user-images.githubusercontent.com/43663588/128895279-84d41e54-06a8-4db8-bc93-1f746b842c72.png">

For this, I'm thinking we don't use any UI. Instead, use a javascript `confirm`, with the text: `Are you sure you want to delete this objective? This action can't be undone!`
