### ISSUE TITLE
Safari renders the MoreInfoBox menu incorrectly

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1684]
The text is shown on top of the dialog:

![image](https://user-images.githubusercontent.com/73479/108117890-8def1680-706b-11eb-914c-e719590a7fc2.png)

**Comment by jpeterson976** [comment]
I have version 14.0.2 (15610.3.7) and it seems to be displaying properly now for me as well.

**Comment by zachberry** [comment]
Thanks all - marking as resolved, will reopen if needed
