### ISSUE TITLE
Safari - Can't click on the break toggle button in the editor

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1685]
(This may be an issue for other chunks with similar in-line menus?)

For reference - this button:

![image](https://user-images.githubusercontent.com/73479/108117984-b545e380-706b-11eb-97ab-53f680619cc8.png)

**Comment by maufcost** [comment]
I believe this issue has been resolved already (recorded on Safari):

![obo](https://user-images.githubusercontent.com/39862359/131875943-729e22d9-ab3c-4800-bc7d-4b9b4cd477a2.gif)

**Comment by walid-i** [comment]
Thanks for letting me know!

**Comment by FrenjaminBanklin** [comment]
Confirmed - this doesn't seem to be a problem any more.
