### ISSUE TITLE
Ability to add lines / spacing between list items

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1696]
An instructor request. This module has a list of problems, but since each item is several lines long it can get difficult to read:

![Screen Shot 2021-02-26 at 9 28 01 AM](https://user-images.githubusercontent.com/73479/109312949-a6062900-7815-11eb-9818-1de7c4af38de.png)

They were able to hack in lines between items, but it no longer uses a proper list:

<img width="841" alt="Screen Shot 2021-02-25 at 11 15 01 PM" src="https://user-images.githubusercontent.com/73479/109312989-b28a8180-7815-11eb-8cf9-bc5859550a4b.png">

Off the top of my head, some ideas:
* Google docs (for example) allows you to hit shift+enter to create a new line in a list without ending the list
* We could add in spacing options (probably the current style, then 0.5em line height between items, then 1em line height between items)

Allowing multiple items in a list would be difficult to do now as each line is considered its own list item. Converting lists to be able to support any type of content would be great, but probably outside the scope of this

**Comment by zachberry** [comment]
Here's the current look of lists:

![image](https://user-images.githubusercontent.com/73479/109314712-b15a5400-7817-11eb-95ee-840ea3c56eb4.png)

Then with 0.5em between items:

![image](https://user-images.githubusercontent.com/73479/109314738-bd461600-7817-11eb-865f-01094cdd3cef.png)

Then with 1em between items:

![image](https://user-images.githubusercontent.com/73479/109314772-c6cf7e00-7817-11eb-8f8c-9d7ad508e029.png)

**Comment by zachberry** [comment]
I'm thinking (for now) we have a style option in the (...) menu, like

![image](https://user-images.githubusercontent.com/73479/109316146-53c70700-7819-11eb-80b6-d810355ee111.png)

Maybe `compact` (Default), `moderate` (0.5em) and `generous` (1em).

Likewise, in XML,

```xml
<List spacing="generous" id="6f7c67d9-4e13-4321-94c8-c43681ad8689">
  ...
</List>
```

**Comment by FrenjaminBanklin** [comment]
This was taken care of in #1881.
