### ISSUE TITLE
Accessibility tweaks to assessment updates in Numeric branch

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#1788]
Found two issues testing the numeric branch with Chromevox

1. When the assessment dialog changes from Submitting your responses to the results dialog Chromevox stays silent, so you don't know that the state of the dialog changed.
2. There's no announcement when a question in an assessment saves your answer. The only indication that something is happening is that the inputs are read as disabled, since the question transitions into a disabled state while saving.

**Comment by deundrewilliams** [comment]
fixed with #1942
