### ISSUE TITLE
Create rubric modal summary

### ISSUE THREAD

**Issue by maufcost** [ucfopen/Obojobo#1791]
For reference: #1780

**Comment by maufcost** [comment]
Almost done with the rubric summary! I am showing all the information set in the rubric in the summary (with a shorter definition for each setting). When it comes to the mod settings, if a user sets, let's say, 10 mod rules, I believe the summary can become unwieldy. Therefore, I had this idea:

![obo_summary_1](https://user-images.githubusercontent.com/39862359/116886936-b06ae780-abf7-11eb-9cc4-58e713b18a28.png)
![obo_summary_2](https://user-images.githubusercontent.com/39862359/116886944-b234ab00-abf7-11eb-95f8-470ac394b77f.png)


Thoughts?

**Comment by zachberry** [comment]
@maufcost Looks good! Nice work!
