### ISSUE TITLE
New URL naming scheme

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#203]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Tuesday May 15, 2018 at 17:36 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/205_

----

Some examples of the new naming scheme:

```
obojobo.ucf.edu/obo-doc/history-of-the-world-00000000-0000-0000-0000-000000000000
obojobo.ucf.edu/obo-doc-version/history-of-the-world-00000000-0000-0000-0000-000000000000
obojobo.ucf.edu/obo-doc-preview/history-of-the-world-00000000-0000-0000-0000-000000000000
obojobo.ucf.edu/visit/history-of-the-world-00000000-0000-0000-0000-000000000000
```

So, want to change the routes as follows:

* [ ] - Change `view/:draftId` to `obo-doc/:textDraftId`
* [ ] - New URL for referring to a specific version: `obo-doc-version/:textDraftId`
* [ ] - Change `preview/:draftId` to `obo-doc-preview/:textDraftId`
* [ ] - Change visit URL from `view/:draftId/visit/:visitId` to `visit/:textVisitId`

`:textDraftId` and `:textVisitId` would have a URL-safe text representation of the object title - I don't have an exact specification at this point, but guessing it would just be a lowercase kebob case version of the title (with a cutoff after a certain length). Then, code would expect the last 36 characters would be the actual id.

If it makes more sense to move these text ids into a new issue then feel free to do so.

**Comment by zachberry** [comment]
Revisiting this and I'm not sure I still agree with the naming convention above. I think this needs more discussion before being implemented.

**Comment by iturgeon** [comment]
I think I'd be fine with just optionally allowing a url encoded title to prefix the UUIDs, but not changing the urls otherwise
