### ISSUE TITLE
Lists don't render correctly in the viewer in Firefox.

### ISSUE THREAD

**Issue by FrenjaminBanklin** [ucfopen/Obojobo#2042]
See:
<img width="788" alt="image" src="https://user-images.githubusercontent.com/1275983/203651976-8b105074-01a6-4e06-a991-30079e04d7a4.png">

They appear to render properly in the visual editor in Firefox, and they render correctly in both places in other browsers.

**Comment by RachelDau** [comment]
PR: #2044
