### ISSUE TITLE
routes/api/drafts/* should be moved elsewhere

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#21]
<a href="https://github.com/iturgeon"><img src="https://avatars2.githubusercontent.com/u/73480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iturgeon](https://github.com/iturgeon)**
_Tuesday Aug 22, 2017 at 21:14 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/22_

----

These files aren't 'controllers/routes', they are just encapsulated queries - they shouldn't be in the routes directory.

Not sure where to put them, but this isn't the right place.

**Comment by rmanbaird** [comment]
routes/api/drafts/ was removed as of commit 78624fd  on May 14, 2018, functionality was at that time rolled into routes/api/drafts.js as a proper router.
