### ISSUE TITLE
Add a storybook for rendering and developing react components

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#211]
<a href="https://github.com/iturgeon"><img src="https://avatars2.githubusercontent.com/u/73480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iturgeon](https://github.com/iturgeon)**
_Thursday May 24, 2018 at 19:00 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/213_

----

https://github.com/storybooks/storybook

**Comment by zachberry** [comment]
Reopened since repos have merged
