### ISSUE TITLE
Data dashboard

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#230]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 21:50 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/232_

----

A page showing the data of a students interaction with Obojobo modules.

**Comment by zachberry** [comment]
Discussed IRL - We could bootstrap this by having a webservice outside of Obojobo which would use a library like [Shiny](https://shiny.rstudio.com/) and R code, allowing you to upload data and get out basic graphics / visualizations
