### ISSUE TITLE
File manager for media uploads

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#237]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Monday Jun 18, 2018 at 14:20 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/239_

----

**Comment by zachberry** [comment]
To clarify - This would allow you to manage files you've uploaded

**Comment by iturgeon** [comment]
For a starting point, here's how materia handles uploading files, I think the interface should mimic the workflow at least.

<img width="837" alt="Screen Shot 2019-08-06 at 11 40 45 AM" src="https://user-images.githubusercontent.com/73480/62554494-3699a480-b83f-11e9-9294-580d26f18695.png">

**Comment by zachberry** [comment]
Some mockups

![image](https://user-images.githubusercontent.com/73479/62799325-87630480-baae-11e9-8564-3ccc9ff60df3.png)

![image](https://user-images.githubusercontent.com/73479/62799334-8af68b80-baae-11e9-9c77-213fd2614335.png)
