### ISSUE TITLE
Mangement Interface

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#249]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Monday Jun 18, 2018 at 18:43 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/251_

----

This is a placeholder issue to implement the module management interface pages. Several issues can be created from this issue.

We need pages that allow authors or groups to manage modules they own (what is currently /editor), to see stats on their modules and for authors (or groups) to publicly display modules they own. This also needs to be searchable.

Here's the current terminology / metaphors:

* **Module** is an Obojobo document created by one or more Authors. A Module can be created, edited, deleted and shared. It can be disabled (no student access) and re-enabled at any time. Modules can be flagged as public meaning they can be added to Collections by other Authors or Teams, can be viewed by anyone and show up in search results. Modules are owned by an Author and optionally are accessible by other Authors, can be partially authored by other Authors, can be owned by a Team, can be in a Group and can be in a Collection.
* **Author** is a single user. Authors can create, delete, edit, enable, disable and share their modules. Authors have a public-facing page listing all of their modules, but can turn this feature off or hide specific modules if desired. They can also join Teams(and leave Teams) and create Groups (and manage Groups) and create Collections (and mange Collections). They can collaborate with other Authors at various capacities given their permission levels (#245 ). 
* **Teams** are (at an abstract level) a simple collection of Authors but typically would represent a community, organization or an academic entity (such as a college or department). Teams can have an optional logo and title. Teams should be able to add or remove Authors at any time by team members, given the team member has the appropriate permissions to do so. Teams can manage their modules. Teams are either public or private - If public then they have a public-facing page which lists their modules (but can turn this feature off or hide specific modules). They can also create and manage Groups as well as Collections.
* **Groups** are a list of Modules by a Team or Author. Groups have a title and optional logo. Groups can be private or public - If public then a public-facing page will exist to view the modules in that Group. A link on the Group will also show up on the Team or Author page. In practice this would allow a Team (or Author) to separate Modules into similar topics (for example, a math department could have a Group for vectors, one for derivatives, one for integrals and so on). Functionally Modules in a Group would work like tags, meaning a Module can appear in more than one Group. In this way they are different than folders on a computer but can be thought of in a similar fashion.
* **Collections** are like a playlist of Modules, which can have an optional order. Collections can be created by Authors or Teams. They also can be made public or private - if public then they have a public-facing page and show up on an Author or Team page. Collections can be included from any source, so for example a Team can create a Collection with modules from other Authors or Teams. Authors or Teams can include their own Modules without issue but can only add other Modules if those Modules are public.

This is a first draft and is open for discussion.

**Comment by zachberry** [comment]
Related #885
