### ISSUE TITLE
Consolidate document xml parser into server

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#25]
<a href="https://github.com/SidTheEngineer"><img src="https://avatars0.githubusercontent.com/u/19176417?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SidTheEngineer](https://github.com/SidTheEngineer)**
_Wednesday Aug 23, 2017 at 18:53 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/26_

----

The document xml parser is its own independent project and required into the root project right now. The goal is to move all of its functionality/tests to the server.

**Comment by zachberry** [comment]
XML parser is now in it's own package thanks to #233 - Closing for now. Can always re-open if we want to do this.
