### ISSUE TITLE
Increase jest version

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#254]
<a href="https://github.com/iturgeon"><img src="https://avatars2.githubusercontent.com/u/73480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iturgeon](https://github.com/iturgeon)**
_Wednesday Jun 20, 2018 at 19:56 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/256_

----

**Comment by zachberry** [comment]
Duplicate, Lapis Lazuli increases this #903
