### ISSUE TITLE
Editor view cannot create a new user

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#265]
<a href="https://github.com/qwertynerd97"><img src="https://avatars3.githubusercontent.com/u/36134301?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [qwertynerd97](https://github.com/qwertynerd97)**
_Monday Jul 09, 2018 at 18:00 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/267_

----

Attempting to launch the Obojobo editor from an LTI results in a user not found error when a user should be created.  This is because the editor route does not seem to call userFromLaunch

**Comment by iturgeon** [comment]
I think this was completely solved in dev/6 with the final bits on this commit:  https://github.com/ucfopen/Obojobo/commit/066a513e6cfb12b3b0373bc3ec9d67d2e7d22a43#diff-9858f82ff8f4b51275ade60e69795994

**Comment by zachberry** [comment]
Tested as well and can confirm that it did create a user with an empty users table. Closing since appears to be fixed.
