### ISSUE TITLE
Improve organization of modules in editor

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#276]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Aug 10, 2018 at 14:08 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/278_

----

If you have a significant number of modules then our current basic editor makes it difficult to find the module you want. Need to come up with a way to improve the UX of this. A search would be easy to implement.

**Comment by zachberry** [comment]
#288

**Comment by gitnix** [comment]
addressed in #288
