### ISSUE TITLE
Change course navigation LTI config to use 'admin' instead of 'members'

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#280]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Aug 17, 2018 at 19:18 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/282_

----

This might allow teachers to see the item but not students

**Comment by zachberry** [comment]
Pull request: #622
