### ISSUE TITLE
Adopt RFC 2119 terminology for Obojobo Node docs

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#303]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Wednesday May 31, 2017 at 19:50 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/7_

----

Should use https://tools.ietf.org/html/rfc2119 ?

**Comment by zachberry** [comment]
Moving to https://github.com/ucfopen/Obojobo-Docs/issues/34
