### ISSUE TITLE
Consider a different approach to rendering StyleableText to HTML

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#305]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Thursday Jun 08, 2017 at 17:33 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/9_

----

Right now:

```
StyleableTextRender(StyleableText) --> MockElement
StyleableTextComponent.render(MockElement) --> HTML
```

However if we don't need the additional features of React-izing the different parts of the StyleableText we could change StyleableTextRender to essentially be of the form

```
toHTML(el) => {
	if(el.nodeType === 'text')
	{
		return el.text
	}

	let attrs = []
	for(let attrName in el.attrs)
	{
		attrs.push(`${attrName}="${el.attrs[attrName]}"`)
	}
	if(attrs.length > 0)
	{
		attrs = ' ' + attrs.join(' ')
	}
	else
	{
		attrs = ''
	}

	return `<${el.type}${attrs}>${el.children.map( (child) => toHTML(child) ).join('')}</${el.type}>`
}
```
(Here 'el' is a MockElement but StyleableTextRender could perhaps use the same idea without having to use the MockElement as a middle-man)

This may be much faster for small elements but may slow-down for large elements.

**Comment by zachberry** [comment]
Closing this as I think the better solution in the future is to migrate to using Slate's rendering and data objects.
