### ISSUE TITLE
Hide letter labels on 'pick-all' questions when no feedback is present

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#321]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Tuesday Sep 19, 2017 at 21:38 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/25_

----

Labels are needed for feedback but look weird and confusing if no feedback exists, see

![image](https://user-images.githubusercontent.com/73479/30616773-5e90fa88-9d61-11e7-9fe4-169873190f8b.png)

**Comment by zachberry** [comment]
Closing this - #255 changes feedback UI which removes pick-all letter labels
