### ISSUE TITLE
Migrate to CSS Grids for document layout

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#346]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Tuesday Jan 02, 2018 at 15:06 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/50_

----

Ex: https://medium.freecodecamp.org/how-to-recreate-mediums-article-layout-with-css-grid-b4608792bad1

**Comment by zachberry** [comment]
I think we should do this before #533
