### ISSUE TITLE
Upgrade to React 16

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#362]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Tuesday Jan 16, 2018 at 20:35 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/66_

----

https://reactjs.org/blog/2017/09/26/react-v16.0.html

This issue is to upgrade to 16 and ensure that there are no breaking changes. Adding React 16 features will be reserved for other issues.

**Comment by gitnix** [comment]
React was updated with #689
