### ISSUE TITLE
Use React 16 fragments

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#363]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Tuesday Jan 16, 2018 at 20:35 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/67_

----

Prereq: #362 

https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings

**Comment by gitnix** [comment]
We are now using React 16, so fragments are available for use. However, I feel like this does not need its own issue. Closing as too granular of an issue. Can reopen later if needed.
