### ISSUE TITLE
Test viewer:leave not being sent (Safari)

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#411]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Mar 16, 2018 at 17:21 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/115_

----

Safari isn't sending `viewer:leave` - Want to find a way to do this if possible, and to see which other browsers may not be sending this event.

**Comment by zachberry** [comment]
Semi-related #651

**Comment by zachberry** [comment]
In testing this was being sent. It was a semi-related issue - a bug with a missing visitId in viewer:return (or viewer:returnFromInactive) I think was causing this to not get sent. Resolved in https://github.com/ucfopen/Obojobo/pull/707

Closing in favor of #707
