### ISSUE TITLE
Home Page (Front-end)

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#458]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Tuesday Apr 17, 2018 at 17:06 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/162_

----

Need a home page designed and implemented.

Related: #160

**Comment by zachberry** [comment]
Closing in favor of #160
