### ISSUE TITLE
Redux!

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#461]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Tuesday Apr 17, 2018 at 17:14 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/165_

----

Would like to migrate from the flux-y stores to using redux (and react/redux router).

**Comment by gitnix** [comment]
duplicate of #106 
closing
