### ISSUE TITLE
edEX imported questions do not have a response type

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#462]
<a href="https://github.com/qwertynerd97"><img src="https://avatars3.githubusercontent.com/u/36134301?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [qwertynerd97](https://github.com/qwertynerd97)**
_Tuesday Apr 17, 2018 at 17:26 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/166_

----

edEX questions contain the class "is-response-type-", and fail to provide a value for the response type.

**Comment by zachberry** [comment]
Tried this on dev/5, looks to have since been resolved.
