### ISSUE TITLE
Assessment loading state overlay

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#464]
<a href="https://github.com/SidTheEngineer"><img src="https://avatars0.githubusercontent.com/u/19176417?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [SidTheEngineer](https://github.com/SidTheEngineer)**
_Thursday Apr 19, 2018 at 15:18 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/168_

----

It has been decided that a good way to go about representing a loading state when clicking assessment action buttons (for now) is by having a loading overlay/modal appear upon some specific assessment events. The idea is to eliminate any delays in UI changes that do not indicate something is happening behind the scenes.

**Comment by zachberry** [comment]
I'm implementing this in #1408
