### ISSUE TITLE
MCAssessment render method needs refactoring - components created

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#468]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Apr 20, 2018 at 20:02 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/172_

----

MCAssessment's viewer-component.js has gotten pretty complex. Some of the sub-components such as the feedback footer and the submitted footer should be turned into their own components.

**Comment by zachberry** [comment]
This has been refactored in #601 and #292
