### ISSUE TITLE
Test support for accented characters

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#508]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Monday May 14, 2018 at 20:59 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/212_

----

Need to make sure that accented characters display, and if not, need to investigate a solution

**Comment by zachberry** [comment]
A quick test shows that Libre Franklin, Roboto Mono and Noto Serif all support accented characters.
