### ISSUE TITLE
Add time values to YouTube chunk

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#525]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Wednesday Jun 13, 2018 at 18:02 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/229_

----

Would be nice to have:

* `time`: What time to start the video at
* `endTime`: Optional end time (not sure if YouTube supports this) - With both `time` and `endTime` specified then a section of a video can be embedded.

**Comment by zachberry** [comment]
Not sure if these needs the embed API or not (related #568 )
