### ISSUE TITLE
Variables shouldn't remove brackets if the variable is not understood

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#528]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Thursday Jun 14, 2018 at 16:00 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/232_

----

For example, if a Text element has `"Here is an {{unknown variable}}"` this should not be modified. Currently the system will remove the brackets but because "unknown variable" is not registered no value will be substituted. Instead the text will be changed to `"Here is an unknown variable"`.

**Comment by qwertynerd97** [comment]
Also, variables that are in the wrong context should not crash the viewer (they should probably fail silently instead)
For example, putting `{{assessment:attemptsRemaining}}` into a Content page causes the viewer to crash because it can't find a parent Assessment to pull the values from
