### ISSUE TITLE
Resumed Attempts should show previous answers

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#529]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Thursday Jun 14, 2018 at 16:38 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/233_

----

Currently attempts can be resumed but the Question UI is not updated. For example, if a three question assessment quiz is started and questions 1 and 2 are answered then those responses are stored in the database. If the page is refreshed then the attempt will be resumed and the previous answers for questions 1 and 2 will still be kept in the database, however both of these questions will appear to the student if they have never been looked at or responded to. If the student doesn't interact with these questions then they will be scored according to how they last responded, however the UI should show their previous answers and should show the questions as having been seen.

I started work on this but put it on hold to wrap up 3.3.0: #51

**Comment by rmanbaird** [comment]
resolution would close #51 and #144
