### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#533]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Thursday Jun 14, 2018 at 17:05 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/237_

----

Need a mobile layout for modules. If possible we should re-work our sass such that it's a mobile first design, meaning

```scss
.rule {
  // Styles for a mobile layout go here

  @media screen and ... {
    // Styles for a larger layout layout go here
  }

  @media screen and ... {
    // Styles for a desktop layout layout go here
  }

  // And so on...
}
```

Likely prereq: #346

**Comment by zachberry** [comment]
Prereq before tackling this issue: #346

**Comment by zachberry** [comment]
The first stab at this was done in dev/7
