### ISSUE TITLE
Show assessment scores and attempt numbers in nav

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#541]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 14:29 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/245_

----

See this older mockup (also in #329 ):

![32524077-f2e09ab2-c3d2-11e7-8a80-3ee5bfa98075](https://user-images.githubusercontent.com/73479/41473167-74e00812-7086-11e8-926a-8ca823223fb4.png)

Would like

1. Assessment scores to display in the nav so that a student doesn't need to navigate to the assessment section to see their score
2. Attempt counts to show in the nav (not shown in mockup). #540 may be the solution to this.

**Comment by zachberry** [comment]
A version of this has been implemented in #1494. Closing this for now, but we can reopen if we want to move towards this design or if we implement multiple assessments.
