### ISSUE TITLE
Extra credit / challenge / follow-up questions

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#548]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 15:17 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/252_

----

A few ideas:

* Imagine an assessment question which is worth 95% credit and a follow up that grants you the remaining 5%
* In assessment a question could be worth an additional amount of points such that the attempt score could be > 100%
* Able to label questions as challenging and be able to present that question in the practice. That could be motivating to students to work towards answering the 'challenge question'.

These can be moved into separate issues as needed.

**Comment by zachberry** [comment]
Moved to discussion https://github.com/ucfopen/Obojobo/discussions/1848
