### ISSUE TITLE
Numeric input question

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#550]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 15:21 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/254_

----

Question type where the answer is one or more text input fields expecting a number. Options should be able to specify an error tolerance, number of significant figures and/or decimal places.

**Comment by zachberry** [comment]
Including a lot of mockups:

Here's an unanswered question:

![screenshot 2019-02-26 15 00 42](https://user-images.githubusercontent.com/73479/53442519-79756780-39d7-11e9-8425-fe0d08bc7966.png)

The input could have content before or after - in this example units are included after the input. Here would be an example of text before:

![screenshot 2019-02-26 15 06 14](https://user-images.githubusercontent.com/73479/53442812-1a642280-39d8-11e9-8c93-01a03c491cad.png)

Optionally we could have some sort of validation before submitting (This may be a separate feature)

![screenshot 2019-02-26 15 07 22](https://user-images.githubusercontent.com/73479/53442866-45e70d00-39d8-11e9-8602-fad93c00946a.png)

A correct response:

![screenshot 2019-02-26 15 08 02](https://user-images.githubusercontent.com/73479/53442891-55665600-39d8-11e9-969b-fdb536fe501a.png)

An incorrect response - In this example there is specific feedback for the input "3.14". A contrived example and poor feedback in this screenshot, but the idea being that there could be feedback for certain values. Perhaps students commonly answer "1" for this question, so in that case, you could explain why that answer is incorrect. Additionally, hints are shown - the first hint once answered incorrectly. Hints could also be added to MC questions (separate issue).

![screenshot 2019-02-26 15 08 29](https://user-images.githubusercontent.com/73479/53443075-d3c2f800-39d8-11e9-88b2-21e8744715a5.png)

If clicked, the hint would be revealed:

![screenshot 2019-02-26 15 12 54](https://user-images.githubusercontent.com/73479/53443153-05d45a00-39d9-11e9-8e3b-199315c8490b.png)

The text becomes 'Hint 1' if multiple hints exist.

Not shown, but hints would persist under the input if the question was attempted again.

If another hint is available then it is shown if the question is answered incorrectly a second time:

![screenshot 2019-02-26 15 14 12](https://user-images.githubusercontent.com/73479/53443270-4d5ae600-39d9-11e9-8d3a-ae584eb63a55.png)

![screenshot 2019-02-26 15 15 27](https://user-images.githubusercontent.com/73479/53443289-5b106b80-39d9-11e9-9a60-d58485c24870.png)

Once all hints are exhausted then you can reveal the answer (If the question allows it. There would be three options: Always allow them to reveal the answer, don't allow them to reveal the answer and only allow them to reveal the answer if they've exhausted all hints)

![screenshot 2019-02-26 15 15 45](https://user-images.githubusercontent.com/73479/53443393-97dc6280-39d9-11e9-9bad-5975730102f7.png)

![screenshot 2019-02-26 15 17 29](https://user-images.githubusercontent.com/73479/53443416-aa569c00-39d9-11e9-801d-d2b9d7b10f9c.png)

Here's an alternate look, with no feedback and no hints:

![screenshot 2019-02-26 15 18 10](https://user-images.githubusercontent.com/73479/53443457-c0fcf300-39d9-11e9-96a1-62c917638c6c.png)

After hashing it out with @qwertynerd97 here's a quick draft of what the data structure might look like:

```
<Question revealAnswer="after-all-hints-shown">
	<QuestionBody>
		<p>Solve for x: 2+2=x</p>
	</QuestionBody>
	<NumericEvaluation>
		<p>x=</p>
		<NumericInput restrict="positive-integer">
			<NumericChoice value="4" score="100" />
			<NumericChoice value="[1,7]" score="0" />
			<NumericChoice value="0" percentError="0.02" score="0">
				<NumericFeedback>
					<p>...</p>
				</NumericFeedback>
			</NumericChoice>
			<NumericChoice value="*" score="0"> <!-- Matches any value -->
				<NumericFeedback>
					<p>...</p>
				</NumericFeedback>
			</NumericChoice>
		</NumericInput>
	</NumericEvaluation>
	<Hints>
		<Hint>
			<p>...</p>
		</Hint>
		<Hint>
			<p>...</p>
		</Hint>
	</Hints>
	<Solution>
		...
	</Solution>
</Question>
```

Note that this uses `QuestionBody`. Currently for questions we don't have a QuestionBody concept, instead, all of the children in the Question except for the last item are the question body. This may be (again) a separate issue.

When answering this question all of the NumericChoices would be checked for a matching value in order. So, if the answer "0" was given:

1. Check if value is `4`. `0 != 4`, so continue.
2. Check if value is anywhere between `1` and `7`. `0` is less than `1`, so continue.
3. Check if value is `0` (with 2% error). This matches, so award the score of `0` and show the matching NumericFeedback.

An additional option would be significant figures, not shown above.

**Comment by zachberry** [comment]
So, here's my current thought on the flow of testing if a NumericChoice "rule" matches or not, based on the given value and the student input

![Obojobo Numeric Question Matching Algorithm (1)](https://user-images.githubusercontent.com/73479/54308012-71a2ef00-45a3-11e9-8513-9efe27f9865a.png)

**Comment by zachberry** [comment]
Related: #558
