### ISSUE TITLE
Short answer question

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#552]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 15:24 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/256_

----

Question type where the answer is one or more text input fields expecting a matching string from a list of supplied possible answers. Want to investigate a possible levenshtein distance algorithm to account for minor spelling mistakes. Potentially raises the need for #551 to account for an instructor forgetting some possible correct answers.

**Comment by vutoan1245** [comment]
My idea on this:

```xml
    <Question>
        <Text>
            <textGroup>
                <t indent="0">Correct inputs are 'Correct Answer 1' and 'Correct Answer 2'</t>
            </textGroup>
        </Text>
        <InputQuestion>
            <InputAnswer answer="Correct Answer 1" score="100" />
            <InputAnswer answer="Correct Answer 2" score="100" />
        </InputQuestion>
    </Question>

```

**Comment by vutoan1245** [comment]
@zachberry @iturgeon I need your opinion on this

**Comment by iturgeon** [comment]
This would be great to have, I could see several iterations:  

Phase 1: multiple answers that use == matching (with space trimming optional?)
Phase 2: multiple answers that use contains matching
Phase 3: multiple answers that use regex-like string matching: `this [.+] works`

```xml
<Question>
        <Text>
            <textGroup>
                <t indent="0">Correct inputs are 'Correct Answer 1' and 'Correct Answer 2'</t>
            </textGroup>
        </Text>
        <InputQuestion>
            <InputAnswer matchMode="exact" answer="Correct Answer 1" score="100" />
            <InputAnswer matchMode="contains" answer="Correct" score="50" />
            <InputAnswer matchMode="pattern" answer="this [.+] works" score="100" />
        </InputQuestion>
    </Question>
```
