### ISSUE TITLE
Formula question types

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#555]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 20:42 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/259_

----

Prereq: #554 

Questions where the answer is a formula. For example:

* Q: What is the equation to determine force?
* A: `f=ma`

Note that the answer would not be a simple string match but would be able to eval the equation. All of the following answers would be correct:

* f=ma
* ma=f
* f=am
* (100-100)+am=f
* and so on

**Comment by zachberry** [comment]
Could be useful: http://asciimath.org/ (and mathquill)

**Comment by zachberry** [comment]
Closing in favor of #554 which covers this feature
