### ISSUE TITLE
Automatically generate alt tags with AI image recognition

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#557]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 20:53 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/261_

----

Would help with accessibility when authors don't supply alt content.

**Comment by zachberry** [comment]
A possible option: https://aws.amazon.com/rekognition/
