### ISSUE TITLE
Sub-problems / Hints

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#558]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 20:54 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/262_

----

Related: #543 #548 #550 

Feature: If you get a question wrong (or ask for a hint) you can either get a hint or a sub-problem. Perhaps the sub-problem gives you 75% credit instead of full-credit.

**Comment by zachberry** [comment]
This is a minor thing, but some insight from this article https://www.blog.google/products/daydream/daydream-labs-teaching-skills-vr/ - Taking a "Hint" can feel like cheating (from personal experience I do want to avoid using hints as long as possible). Maybe there's another way we can phrase this or label this - Maybe "Clue", or "step-by-step", or somehow making hints not optional but required to progress?

**Comment by zachberry** [comment]
More hint mockups at #550
