### ISSUE TITLE
Step-by-step practice problem mode (Solve problem with you / Problem walkthrough)

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#563]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 21:04 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/267_

----

From Dr. Chen's Oct 2017 student survey:

```
The only thing I did like about webassign were the tutorial questions in which the problems were solved step by step with you.
```

**Comment by zachberry** [comment]
Here's a quick mockup of this:

![screenshot 2019-02-26 15 43 37](https://user-images.githubusercontent.com/73479/53444877-49c95e00-39dd-11e9-9ad7-81be1e6a23fa.png)

**Comment by zachberry** [comment]
Potentially a question hint could be to open a walkthrough, helping you solve a similar problem:

![screenshot 2019-02-26 15 46 38](https://user-images.githubusercontent.com/73479/53445093-c8be9680-39dd-11e9-8882-0bcf56f68bbe.png)

**Comment by iturgeon** [comment]
I don't think I'm ready to let this one expire. Some version of a multi-step question is very desirable to us.

**Comment by zachberry** [comment]
Keeping track of this in a discussion: https://github.com/ucfopen/Obojobo/discussions/1845
