### ISSUE TITLE
Events needed for video (YouTube)

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#568]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 21:23 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/272_

----

We are not keeping track of when videos are played, paused, scrubbed and so on. We should also have Caliper equivalents.

**Comment by zachberry** [comment]
This is now possible thanks to #1007

**Comment by zachberry** [comment]
So for example, when the user clicks play on a YouTube video a 'media:played' event should be fired. The media-store could listen for that event and sent it to the events api, with data like the videoId being played and the current playhead position. We'd then want to do this for all the major actions, like stop, pause, scrub, and whatever other reasonable things we can tap into with the YouTube embed API (like if they enabled or disabled closed captions, if that's possible to determine).

Phase two of this would be to make YouTube video respond to events. So for example a button could fire off a 'media:play' event which would start playing a YouTube video. But this can be moved to a second issue (you'd need to add fields in the visual editor for the Triggers/Action dialogs).

Phase three would be to be able to respond to user actions, so for example there could be a trigger on an OboNode for WHEN a 'media:played' event is fired then something can happen. But we would need to setup a trigger for when a specific media was played, and I don't think the triggers can support that yet.
