### ISSUE TITLE
Coaching: Recommend students to move on after a time limit has passed

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#574]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Friday Jun 15, 2018 at 21:54 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Document-Engine/issues/278_

----

Cut off students after a set time limit or if they have been looking at a question past the current average. Idea being that after a point looking at a problem longer doesn't aid with learning - it would help more to move on and come back. Perhaps a message is shown directing them to try another problem. Could market/label this feature as "coaching"

**Comment by zachberry** [comment]
Closing in favor of #967
