### ISSUE TITLE
update sample object to include 3.3.0 features

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#579]
<a href="https://github.com/iturgeon"><img src="https://avatars2.githubusercontent.com/u/73480?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [iturgeon](https://github.com/iturgeon)**
_Thursday May 10, 2018 at 16:55 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Docment-XML-Parser/issues/6_

----

**Comment by gitnix** [comment]
addressed in #631
