### ISSUE TITLE
Adjacent styled text tags collapse spaces

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#626]
The following code

```
<p><b>A</b> <i>B</i> <b>C</b></p>
<p><b>A</b> and <i>B</i> and <b>C</b></p>
```

Produces

![screenshot 2018-10-31 15 48 12](https://user-images.githubusercontent.com/73479/47814547-618d2000-dd24-11e8-81a8-ad189d64eceb.png)

The top line has the styled text sitting next to each other without the spaces in-between. The bottom line of text works as expected.

**Comment by vutoan1245** [comment]
Reason: white spaces between XML tags are ignored. 

Similar to this example:
```xml
<TextGroup>   <Text /></TextGroup>
```
White spaces between `<TextGroup>` and `<Text />` have no overall effect. 

`xml-js` have an option to ignore white spaces `captureSpacesBetweenElements: true` (https://github.com/nashwaan/xml-js/issues/29), but it will affect the entire file.

Currently, I don't think `xml-js` has the feature to use this option conditionally.

**Comment by vutoan1245** [comment]
One possible solution is to use a different package https://www.npmjs.com/package/xml2js
This package has a lot more features but it will take a lot of time.
