### ISSUE TITLE
Page titles can't be numbers

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#627]
1. Create a page with a title of `1`
2. Save, preview document

Result: An error is thrown as a result of the line at https://github.com/zachberry/Obojobo/blob/5925e5d99bccbd2cc5961c2f656d36a80a91c739/packages/obojobo-document-engine/ObojoboDraft/Pages/Page/viewer.js#L26-L27

In other words, `1` comes through as a number, not a string.

Easy fix, but I haven't tested other titles. Want to make sure there aren't similar conversion issues elsewhere (not just Pages).

**Comment by rmanbaird** [comment]
The same error was thrown with a number as the title of an Assessment
