### ISSUE TITLE
WYSIWYG: Insertion Behavior of Invalid Nodes

### ISSUE THREAD

**Issue by gitnix** [ucfopen/Obojobo#629]
Currently, if an invalid node is inserted into the document (such as a figure being inserted into a table cell), the editor will ignore it and instead move the cursor to the next node. It would probably more intuitive to not move the cursor and display a modal or such to notify the user that the operation is not allowed. In its current form, a user may wonder if something went wrong with the insertion. Another possibility is to conditionally render the acceptable nodes to insert based on cursor position.

**Comment by qwertynerd97** [comment]
We altered the way the insertion works, which made this outdated
