### ISSUE TITLE
Heartbeat visit check to prevent multiple windows / check login

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#652]
Users can have two Obo modules open. Need to implement some sort of heartbeat check and set other open windows into a locked state. This could also be used to ensure the user is still logged in (or the LTI hasn't expired), and lock the module when this has passed. Optionally show a dialog that the lock-out will happen soon.

**Comment by iturgeon** [comment]
Just looking, we may able to use https://www.npmjs.com/package/sysend
