### ISSUE TITLE
Query errors being displayed in response

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#673]
Example:

Start a visit to a module, then modify the visit ID. Refresh the page, then, since that visit ID doesn't exist the query in the Visit model's fetchById method will fail. This throws a QueryError, and the end result is that the page displays

```
Server Error: QueryResultError { code: queryResultErrorCode.noData message: "No data returned from the query." received: 0 query: " SELECT is_active, is_preview, draft_content_id FROM visits WHERE id = '39fca5a1-5468-4251-ad49-8a8744e5c95e' ORDER BY created_at DESC LIMIT 1 " }
```

The visit model should probably fail more gracefully, but the crux of this issue is that the query text is being rendered via the error mechanism in the unexpected method for express_response_decorator. 

Need to reduce the amount of error messaging that is being sent back in the response.

**Comment by gitnix** [comment]
addressed in #675
