### ISSUE TITLE
Safari: Hamburger menu icon missing

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#677]
See:

![screenshot 2019-01-29 10 37 53](https://user-images.githubusercontent.com/73479/51919731-0cf45200-23b2-11e9-8d11-38d04f6aba15.png)

**Comment by qwertynerd97** [comment]
In safari, The Obojobo label on the bottom left appears duplicated as well
<img width="306" alt="screen shot 2019-01-29 at 1 35 00 pm" src="https://user-images.githubusercontent.com/36134301/51931462-dc6ce200-23ca-11e9-9da5-75ee5395587e.png">
