### ISSUE TITLE
'pick-all' questions incorrect message displays weirdly with small width screen sizes

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#678]
This was tested in IE11 but it may be an issue everywhere:

![screenshot 2019-01-29 13 56 16](https://user-images.githubusercontent.com/73479/51932836-fcea6b80-23cd-11e9-9dd9-64bd8adf10b9.png)

**Comment by qwertynerd97** [comment]
It's definitely an issue with Safari too.
