### ISSUE TITLE
Canvas "Test Student" doesn't authenticate

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#688]
It looks like Canvas sends no email with the test student and it causes errors when trying to view assignments as the test student

**Comment by iturgeon** [comment]
looks like test student sends no email:
```
lis_person_contact_email_primary=
lis_person_name_family=Student
lis_person_name_full=Test+Student
lis_person_name_given=Test
lti_message_type=basic-lti-launch-request
roles=Learner
user_id=... (changes with every time you reset the student user)
custom_canvas_user_id= ... (changes with every time you reset the student user)
custom_canvas_user_login_id= ... (changes with every time you reset the student user)
```

**Comment by iturgeon** [comment]
At best, I think we'd have to match a lot of these params to assume it is the test student.

There is also a custom canvas variable you can configure to ask for - `Canvas.masqueradingUser.id` https://canvas.instructure.com/doc/api/file.tools_variable_substitutions.html

**Comment by iturgeon** [comment]
I added a pr to ask for the masquerading use https://github.com/ucfopen/Obojobo/pull/944/files

**Comment by zachberry** [comment]
This is still an issue, student view in Canvas gives you the Internal Server Error page
