### ISSUE TITLE
Combine duplicated code - have Viewer and Editor share code

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#708]
In reviewing https://github.com/ucfopen/Obojobo/pull/585 there are a few cases where code is duplicated across the Viewer and Editor projects (for example, code to generate UUIDs). Need to find a clean solution so that these can share the same code, removing duplication. Perhaps that is to 'packageify' the Viewer and Editor into their own packages.

**Comment by gitnix** [comment]
Currently, we can get common code from `obojobo-document-engine/src/scripts/common` package
