### ISSUE TITLE
Editor CSS Refactor/Cleanup

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#713]
The editor has a lot of selectors that may bleed into Chunk children as they lack specificity. Instead of fixing a few at a time in different PRs I'm making this issue to do a blanket sweep to correct these.

Not a high priority in order to fast-track the editor, but once that is stable I'd like to go back and refactor these.

To fix:
1. For nested selectors, use the child combinator: https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator
2. For classes that aren't nested, they need a complex selector like `obojobo-draft--editor--component--*` so they'd be unlikely to accidentally bleed styles in a child of that element.

**Comment by vutoan1245** [comment]
It seems like it has been fixed with the new editor
