### ISSUE TITLE
Refactor Table UI in the editor

### ISSUE THREAD

**Issue by qwertynerd97** [ucfopen/Obojobo#722]
Right now the UI for the table is very basic and should probably be cleaned up to match the design of Obojobo.  We should add a delete button for the whole table, and refactor the placement of the row and column delete buttons, as well as the buttons below the table

**Comment by zachberry** [comment]
Some mockups:

First, the button with the menu closed. Left is current, right is the mockup:

![image](https://user-images.githubusercontent.com/73479/90258128-1a4b2300-de16-11ea-954a-e5780f72ff6f.png)

Next, the menu open - Left is current, right is the mockup (showing the first item being hovered over):

![image](https://user-images.githubusercontent.com/73479/90258196-2df68980-de16-11ea-9ada-c4de5a39d7c8.png)

**Comment by zachberry** [comment]
I think this menu would also benefit with some icons, but we can spawn that into a new issue
