### ISSUE TITLE
Copy and Paste in Editor

### ISSUE THREAD

**Issue by qwertynerd97** [ucfopen/Obojobo#724]
Copying text from the editor and then pasting it back into the editor fails to paste the content.  This may be due to how Slate represents data; we can probably override this with a plugin.

**Comment by qwertynerd97** [comment]
Notes on copy-pasting with merging:
We have 4 types of nodes: 
- Void nodes (contain no text in the editor, only modal properties)
- Single nodes (contain only one line of text)
- Multi nodes (contain one or more lines of text)
- Parent nodes (contain other nodes, but no text of their own)

Therefore, there are 16 types of paste operations:
1. Void into Void - Insert pasted node at end of receiving node
2. Void into single - Insert pasted node into single node, split single node if pasted in the middle
3. Void into multi - Insert pasted node into multi node, split multi node if pasted in the middle
4. Void into parent - Does not actually exist (pasting into parent is actually pasting into void, single, or multi inside parent)
5. Single into void - Insert single at end of void node
6. Single into Single - Paste only the text into the receiving node
7. Single into multi - Paste only the text into the receiving node
8. Single into Parent - Cannot happen, see # 4
9. Multi into void - Insert multi at end of void
10. Multi into single - If at end of single: insert the first line of multi into single, and then create a multi after single with rest of lines.  If at start of single, insert the last line of multi and then create multi before single with rest of lines.  If in the middle of single and only one line in multi, add single line of text.  If in middle of single and multiple lines in multi, split single, add the first line to the first single, add the last line to the last single, and then create a new multi in between the singles to hold any extra lines
11. Multi into multi - convert lines to correct type and insert, pre- or post-pending as necessary
12. Multi into parent - Cannot happen, see # 4
13. Parent into Void - Insert pasted node at end of receiving node
14. Parent into single - Insert pasted node into single node, split single node if pasted in the middle
15. Parent into multi - Insert pasted node into multi node, split multi node if pasted in the middle
16. Parent into parent - Cannot happen, see # 4

These make the most sense if only pasting one node; if pasting multiple nodes, use this decision tree to paste the first node, and then simply insert successive nodes.

Current Obojobo nodes and their (potential) types:
ActionButton - Parent node containing Single node label + void node actions (pasting only actions would create an action button with a blank label)
Break - void node
Code - multi node
Figure - Parent node containing void image + single node caption (pasting only image would create a Figure with a blank caption, pasting into the image would insert before instead of after)
Heading - single node
Html - single node (counterintuitive, but HTML nodes use soft breaks instead of lines)
IFrame - void node
List - multi node
MathEquation - void node
MCAssessment - parent node
Question - parent node
QuestionBank - parent node
Table - multi node/ void node? 
Text - multi node
Youtube - void node
Page - parent node
Assessment - parent node

**Comment by iturgeon** [comment]
Copy and paste is causing a white screen of death in 7.0.4.  When copy/pasting text with styling or other markup, the editor will often be unrecoverable.  

Specifically when pasting into Headers.  Bug report indicates that entering text before pasting will reduce the likelihood of a halting error
