### ISSUE TITLE
Move XML parsing into chunks

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#780]
Adding chunks sometimes require us to modify the XML parser, which is less than ideal. Instead each content type could have it's own XML parser and the root XML parser could call on each content type's XML parser.

**Comment by iturgeon** [comment]
Materia chunk brought some of the changes needed for this to happen. 

check out https://github.com/ucfopen/Obojobo/blob/dev/19-serendibite/packages/obonode/obojobo-chunks-materia/materia-format-parser.js.  It's registered in the chunk's manifest (index.js)
