### ISSUE TITLE
PDF OboNode

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#793]
I'm sure there's a PDF js library out there we could use. Would embed a PDF into an Obo document. Optional features would be to specify a page to start on or a range of pages to display instead of the whole document (if the library allows this).

Has implications into accessibility, would need to make sure that content is accessible to screen readers.

**Comment by iturgeon** [comment]
https://github.com/wojtekmaj/react-pdf looks like a great start for this
