### ISSUE TITLE
Add the necessary APIs to allow Slate to work on IE11

### ISSUE THREAD

**Issue by qwertynerd97** [ucfopen/Obojobo#800]
According to the Slate documentation: 

> For older browsers, such as IE11, a lot of the now standard native APIs aren't available. Slate's position on this is that it is up to the user to bring polyfills (like https://polyfill.io) when needed for things like el.closest, etc. Otherwise, we'd have to bundle and maintain lots of polyfills that others may not even need in the first place.

We should look into what polyfill libraries are needed to make the Visual Editor work in IE11

**Comment by zachberry** [comment]
We follow the same browser support as Instructure Canvas (https://community.canvaslms.com/docs/doc-10720) who recently dropped IE11 support - "On August 3, 2019, Internet Explorer 11 will no longer be supported as a Canvas browser"

Closing since we no longer support IE11
