### ISSUE TITLE
Editor IFrame example rendering weirdly

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#811]
See:

![Screenshot 2019-04-17 14 38 28](https://user-images.githubusercontent.com/73479/56312642-9d734080-611e-11e9-9559-f77b62fb2497.png)

**Comment by vutoan1245** [comment]
<img width="782" alt="Screen Shot 2019-06-04 at 5 22 50 PM" src="https://user-images.githubusercontent.com/23706824/58914828-7cc27280-86ed-11e9-9c9a-c6d92c7a3beb.png">
@zachberry Check if the problem still exists
