### ISSUE TITLE
Navigation control not editable in visual editor

### ISSUE THREAD

**Issue by Zhongzhou** [ucfopen/Obojobo#817]
There doesn't seem to be a way to add actions such as nav:lock and nav:unlock triggered by entering or exiting a page or assessment, using the visual editor. This is critical for creating useful modules via the visual editor.

**Comment by qwertynerd97** [comment]
Zach and I talked about this in person, and it should be pretty easy for us to add a very basic form of this functionality based on existing code.
Here are my notes on where to look for similar code in our codebase
- Displaying the information: ActionButton (packages/obonode/obojobo-chunks-action-button/editor-component.js)
- Displaying a Custom Modal and returning data from it: Action Button (packages/obonode/obojobo-chunks-action-button/new-action-modal.js), Figure (packages/obonode/obojobo-chunks-action-button/image-properties-modal.js), Math Equations (packages/obonode/obojobo-chunks-action-button/math-equation-properties-modal.js)
 - Updating the data in the Slate Node: ActionButton (packages/obonode/obojobo-chunks-action-button/editor-component.js)
