### ISSUE TITLE
update caliper-js github repo url

### ISSUE THREAD

**Issue by bracken** [ucfopen/Obojobo#824]
Hi, we've removed the old "public" version of the Caliper-js library because it wasn't updated any more and was causing confusion. If you want to update this project you can change your package.json dependency to:

```json
"caliper-js-public": "https://github.com/IMSGlobal/caliper-js.git#v1.0.0",
```

when I did a search on your project it showed up here:
https://github.com/ucfopen/Obojobo/blob/bbe717dffa40b0f042206fa71c92cc9bf57588bd/packages/app/obojobo-express/package.json

**Comment by zachberry** [comment]
Thanks @bracken, we'll change it
