### ISSUE TITLE
Visits Table needs additional Indices

### ISSUE THREAD

**Issue by gitnix** [ucfopen/Obojobo#836]
`create-visitis-table` migration returns before creating all indices. Need to remove the non-running code from `create-visits-table` migration and move it into a new migration.

**Comment by iturgeon** [comment]
seen here https://github.com/ucfopen/Obojobo/blob/bbe717dffa40b0f042206fa71c92cc9bf57588bd/packages/app/obojobo-express/migrations/20180124212301-create-visits-table.js#L43-L45
