### ISSUE TITLE
Repeated 'Error: Reached exceptional state while reloading state for...' error logs

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#843]
This is in reloadAttemptStateIfReviewing in attempt-end.js. A few theories:

1. `review` is being set to a non-expected property, maybe "noAttemptsRemaining" instead of "no-attempts-remaining"
2. `review` is not set, and perhaps we aren't planning for that attribute not to exist
3. Log out is happening, somehow this method still runs but data doesn't exist

**Comment by vutoan1245** [comment]
I couldn't find this error in `dev/8-onyx`

**Comment by zachberry** [comment]
Marking as resolved, if this still is an issue reopen
