### ISSUE TITLE
Need to add resource link ids

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#88]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Wednesday Jan 03, 2018 at 15:44 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/90_

----

Related: #83 

Right now if you create two LTI assignments with the same draft these won't work as two different assignments. The second assignment will appear as if you've already completed it.

Tables that store student access such as view_state, attempt tables and such should add a resource link ID to keep track of this. Or we need to add this to the launches table and hinge off the launch more.

**Comment by zachberry** [comment]
Additionally this may solve an issue where a student taking a course cannot re-take the same module as their previous score data still exists
