### ISSUE TITLE
Consider migrating from express to koa

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/Obojobo#9]
<a href="https://github.com/zachberry"><img src="https://avatars2.githubusercontent.com/u/73479?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zachberry](https://github.com/zachberry)**
_Thursday Jun 29, 2017 at 19:15 GMT_
_Originally opened as https://github.com/ucfcdl/Obojobo-Next/issues/10_

----

All news to me, but I guess Koa is the "new express" as current express development has slowed - conversation at https://www.reddit.com/r/javascript/comments/4fjzf9/koa_vs_express/

Express is serving us nicely so I don't consider it a pressing need but I could see us wanting to migrate in the future.

**Comment by zachberry** [comment]
Closing as this would be a significant change and I see little pressure at the moment to switch, we can always re-address this issue at a later date.
