### ISSUE TITLE
UI to edit visual editor documents as XML (Using JSON->XML Parser)

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#902]
I'm not sure yet what the UI of this looks like - Either there's a button to switch between JSON and XML or when you go to edit a visual editor document it's auto-converted to XML, but the desire is to use the new parser (See #718 ) to allow authors to switch to a 'code view' to have them edit documents created in the visual editor as XML instead of JSON.

**Comment by vutoan1245** [comment]
This was implemented in #922
