### ISSUE TITLE
Add Observer (and other roles?) to canPreviewDrafts

### ISSUE THREAD

**Issue by zachberry** [ucfopen/Obojobo#998]
Carnelian added the canViewAsStudent role and currently only Learner is defaulted to have that role. As a result, Observers can no longer "observe" modules because of our new stricter rules. The reason we limited viewing to Learner was because that is (technically) the only role that can send scores via LTI, and we wanted to prevent an issue where sending scores would error out and confuse people. However by doing so we can no longer let Observers observe and that feels wrong.

Easiest solution to simply add Observer (and any other roles that make sense) to canPreviewDrafts by default.

**Comment by iturgeon** [comment]
added in v7.1.4
